### ISSUE TITLE
Local monitoring port

### ISSUE THREAD

**Issue by Angel996** [todxx/teamredminer#1]
Hello.

Please add a simple TCP monitoring API, at least global hashrate. I have a script that updates algo changes based on hashrate, I need it to run benchmarks.

And thanks for your great miner! :1st_place_medal:

**Comment by todxx** [comment]
Hi @Angel996,
We are planning on adding API support, but it will be a little while until we have it working.  I'll keep this ticket open and post updates regarding progress if we have news.

**Comment by todxx** [comment]
API support has been added in the last release.  We chose to implement a subset of the sgminer API as it makes it easier to integrate with existing monitoring tools.  I believe minerstat and awesome miner have already added support.
