### ISSUE TITLE
API failed writing client response.

### ISSUE THREAD

**Issue by zjwhsm** [todxx/teamredminer#10]
API failed writing client response.

why?

![image](https://user-images.githubusercontent.com/34436611/48887407-25a03300-ee6a-11e8-86cd-51de3c1d3ddd.png)
![image](https://user-images.githubusercontent.com/34436611/48887430-2fc23180-ee6a-11e8-9865-0af7ec2f1598.png)

**Comment by todxx** [comment]
This means that the API code failed to send the response of an API request to the client that requested it. This is most likely because of either network problems, or because the API client closed the connection before the response could be sent back.

**Comment by zjwhsm** [comment]
Thank you....

Let me try it on.
