### ISSUE TITLE
Weird error Ubuntu LTS Server

### ISSUE THREAD

**Issue by ArSd-g** [todxx/teamredminer#120]
Hi, Any clue to resolve this?
![Capture d'écran Deepin_zone de sélection _20200421032035](https://user-images.githubusercontent.com/42816950/79814696-31ee2f80-837f-11ea-93ff-6bee7a9fc285.png)

**Comment by todxx** [comment]
That is the equivalent of a segfault happening on the GPU.  Typically we see this due to broken drivers or kernels.

Please try out the lastest release and reopen this issue if the problem persists.
