### ISSUE TITLE
please support r9 390 card

### ISSUE THREAD

**Issue by Kudabelangfx** [todxx/teamredminer#124]
hello pls support r9 390 card for kawpow RVN

**Comment by pmfrulez** [comment]
please support r9 280x tahiti gpu too ....Im here to test if you nead, all version s of rx cards + r9 
280x  ...
mr.pacy.mf@gmail.com

**Comment by todxx** [comment]
Sorry, but we only support GCN 1.2 and newer cards (Fiji/Polaris and newer).  Unfortunately there are significant changes required to support older GCN ISAs.
