### ISSUE TITLE
Freeze Windows 10 when one Vega crash

### ISSUE THREAD

**Issue by rb116** [todxx/teamredminer#13]
Hi,
I have been testing 0.37 on Win10,1803 , 18.6.1 for the last 3 days. Apparently it crashes on oneof my Vega 56 to 0 hash but the miner still running which is fine. I tried Ctrl c, Ctrl break to stop your mining sw but it got lock up on tht crash Gpu. Task Mgr showing 100%, Sending data as shown in Ethernet port. I force close the cmd screen of trm mining sw but no luck. I hv to poweroff the windows since proper windows shutdown will stuck too.
Anyway, good job and keep up the good work. I do like your miners. lower power consumption and better hash than srb 1.70,xmrig and stak.  Most importantly,  it is showing more or accurate hash on pool dashboard as compares to SRB.. ya SRB. At least I know tht your mining sw not connecting to your dev pool quietly
1. Need status api on mining sw, I cant even press H to chk hash, connection, fan speed and temp.
2. improve on Stability. 
3. Does it allow 2 or mirror pool in bat file?
4.  Shutting down properly.

**Comment by todxx** [comment]
The miner comes with an sgminer compatible API.  It is supported by many monitoring tools, such as Awesome Miner.
We do not yet support pool failover, this should be added in the next release.
In version 0.3.8 we made it so hitting ctrl-c twice should kill the miner immediately, although if your drivers are hung/crashed, this may not have much effect.  Also there is now a watchdog feature which can run a provided script when a crashed GPU is detected.

**Comment by phreaknik** [comment]
@todxx is there a man-page that describes the watchdog usage? I would like to make my system more robust with a good watchdog script

**Comment by todxx** [comment]
Closing old issue since many of these issues have been addressed.  Please re-open or create a new issue if the problems here are still present in the most recent release.
