### ISSUE TITLE
Gpu program problem with instalation on usb

### ISSUE THREAD

**Issue by Ddish994** [todxx/teamredminer#152]
Im downloading teamredminer program on computer then i cant put on usb it says Error opening source sorry bad english.Please help i cant start mining

**Comment by Ddish994** [comment]
![20201025_180132](https://user-images.githubusercontent.com/73438297/97114048-7ff93c80-16ee-11eb-8edb-fbbd80942511.jpg)
Im downloading teamredminer program on computer then i cant put on usb it says Error opening source sorry bad english.Please help i cant start mining

**Comment by UselessGuru** [comment]
What exactly are you trying to achieve?

The miner zip file is not intended to be put on a USB stick like this.
It is NOT a bootable image file.

**Comment by Ddish994** [comment]
> What exactly are you trying to achieve?
> 
> The miner zip file is not intended to be put on a USB stick like this.
> It is NOT a bootable image file.

How to fix this to put file and miner mail to usb and start mining im new in this please help Best Regards

**Comment by setuidroot** [comment]
@Ddish994 

As UselessGuru said, this is **not** a bootable file.  This is not an operating system.  **Forget Etcher**.  This is a ZIP archive with TRM (Teamredminer.exe executable binary) inside the ZIP archive.

Download and install 7zip (free software for ZIP archives.)

7zip is here: https://www.7-zip.org/

Download windows 64 bit installation .exe here: https://www.7-zip.org/a/7z1900-x64.exe

^ Download the above "7z1900-x64.exe" file and install it (right click, run as Admin and follow the installer.)

You can remove WinRAR or any other BS zip archive software. **7zip** is the one and only.

Now that you have 7zip installed, download the latest TRM release (ZIP archive) here:  https://github.com/todxx/teamredminer/releases/download/0.7.16c/teamredminer-v0.7.16c-win.zip

Now go to downloads, right click on "teamredminer-v0.7.16c-win.zip" and find "Extract All" (or **Extract** Here; "Extract" *something*, I don't remember) with *7zip*.

7zip will open and extract the TRM release zip archive.  You should now see "teamredminer.exe" (with many other files that TRM comes with: *.bat files for running the miner (.exe) and README information files.)

Now you just run "teamredminer.exe" on Windows.  There is **no** operating system to install.  Forget Etcher and forget the USB flash drive.  TRM is not an operating system.  TRM is a miner executable *binary* (.exe) that you run on Windows (or the Linux binary on Linux.)

**Comment by Ddish994** [comment]
Problem solved ty all
Best Regards
