### ISSUE TITLE
Unexplained crashes 

### ISSUE THREAD

**Issue by minersunited** [todxx/teamredminer#157]
I have recently been testing out TeamRedMiner on some older 4gb RX 470 rigs I had laying around. It is working great for the most part, but I am getting some unexpected crashes that I cannot figure out. I am running TRM on ubuntu 18 with amdgpu-pro drivers 20.10.

I have turned watchdog off, and debug mode on so I can try and find the error in the logs, but I do not see anything unexpected. When watchdog was enabled and the miner would crash, my watchdog script was NOT executed and the rig did not reboot. After TRM crashes, I can restart the service and it will begin mining normally again. I do not see any errors whatsoever in my log file. Has anyone else experienced this behavior?

**Comment by CodySchrank** [comment]
I'm also getting very random crashes.

Windows 10 
Adrenaline 20 drivers
5700xt

Been happening anywhere between 1 and 24 hours after starting the script.  Not using watchdog.  The machine itself is fine, I can restart the script and it will start mining again.

**Comment by minersunited** [comment]
I do not think that is my issue, no antivirus on a stock install of ubuntu server. 

Anyone else having anything similar? I have completely reinstalled OS and tested on multiple different hardware setups but this is still happening a good deal of machines.

**Comment by minersunited** [comment]
Figured this out, the RAM allocation (eth_4g_max_alloc) for mining ethereum on 4gb cards was set too high. Reducing this value from 4078 to 4070 and have not had any more crashes.
