### ISSUE TITLE
Claymore API drops after some time (~1-2+ day)

### ISSUE THREAD

**Issue by man55** [todxx/teamredminer#172]
This is a great feature, thanks!
I use it to monitor the TRM on RaveOS through Awesome miner.
But after a while the API falls. This happens in about a 1-2 day or more. I have watched this since the introduction of this feature.
ApiReport is empty.
The only thing that helps to solve the problem is restarting the miner, after which the API starts working again. 

Please correct it

![Screenshot 2021-01-04 114532](https://user-images.githubusercontent.com/30772900/103522080-86402d80-4e82-11eb-9786-19c0a4d291d1.jpg)
.

**Comment by ddowhy** [comment]
yes seeing this as well across all my miners.  like you said, happens after a day or two of uptime.

![connection_limit](https://user-images.githubusercontent.com/6941337/103574898-c01f2d00-4e9e-11eb-873f-cf896eb3bda0.JPG)

**Comment by man55** [comment]
> yes seeing this as well across all my miners. like you said, happens after a day or two of uptime.
> 
> ![connection_limit](https://user-images.githubusercontent.com/6941337/103574898-c01f2d00-4e9e-11eb-873f-cf896eb3bda0.JPG)
Yes, I see the same in my miners log

**Comment by man55** [comment]
Fixed in 0.8.0
Thank you!
