### ISSUE TITLE
How to dual mining ETH + ZIL?

### ISSUE THREAD

**Issue by Chiqui1234** [todxx/teamredminer#178]
Hi! I want to suscribe in this pool: https://ezil.me/ but I have suscription errors and can't mine:
```
ene 13 13:30:17 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:17] Pool eu.ezil.me connecting to address 51.89.112.180.
ene 13 13:30:17 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:17] Pool eu.ezil.me successfully connected to address 51.89.112.180.
ene 13 13:30:17 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:17] Pool eu.ezil.me connection was closed by the pool.
ene 13 13:30:17 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:17] Pool eu.ezil.me switching to stratum mode.
ene 13 13:30:18 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:18] Pool eu.ezil.me connecting to address 51.89.112.180.
ene 13 13:30:18 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:18] Pool eu.ezil.me successfully connected to address 51.89.112.180.
ene 13 13:30:18 PC-ATHLON teamredminer[3918]: [2021-01-13 13:30:18] Pool eu.ezil.me subscribe failed. (246 ms)
```

I execute TRM with (note I have ETH + ZIL wallet in the **-u** parameter):
```bash
teamredminer -a ethash -o stratum+tcp://eu.ezil.me:5555 -u 0x3eEe4EE63a99AAb21D4294Ad320F3e54E7d618a3.zil104cz5hkqm6ppfwljq35rxtfjhwz7z9569jzhs2 -p x --eth_config=A512 --eth_dag_cache=0 --fan_control=:::80
```

How can I mine in this dual mining pool?

**Comment by Chiqui1234** [comment]
bump!

**Comment by pdieppa** [comment]
> bump!

My 5700XTs were able to mine ETH and ZIL under HiveOs. My Vii running under Windows was not happy with TRM. Only lolMiner worked. I'll continue trying since I really like TRM. In my case, after connecting successfully, no data would received received. It just sits there after successful connection message. I like ZIL, I got my first 47 of them yesterday.

**Comment by ProkVS** [comment]
Try --eth_stratum_mode=ethproxy

**Comment by Chiqui1234** [comment]
> --eth_stratum_mode=ethproxy

that didn't worked :(

**Comment by Chiqui1234** [comment]
Well, this **start.bat** throws me an error related to pool's login:
```bash
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
set GPU_MAX_HEAP_SIZE=100
set GPU_USE_SYNC_OBJECTS=1
teamredminer.exe -a ethash -o stratum+tcp://eu.ezil.me:5555 -u 0x3eEe4EE63a99AAb21D4294Ad320F3e54E7d618a3.zil104cz5hkqm6ppfwljq35rxtfjhwz7z9569jzhs2 -p x --eth_stratum_mode=ethproxy -d 0 --enable_compute
pause
```

Error:
![imagen](https://user-images.githubusercontent.com/42920751/105632930-979ea900-5e34-11eb-8594-8bf099d46760.png)

**Comment by ProkVS** [comment]
Сonnect your monitor to iGPU or other GPU during the test and run cmd as administrator:
`teamredminer.exe -a ethash -o stratum+tcp://eu.ezil.me:5555 -u 0x3eEe4EE63a99AAb21D4294Ad320F3e54E7d618a3.zil104cz5hkqm6ppfwljq35rxtfjhwz7z9569jzhs2 -p x --eth_stratum_mode=ethproxy --eth_worker=luckyNavi --eth_config=A --eth_dag_cache=0 --enable_compute`
The most important parameter is "luckyNavi", it won't work without it )))

**Comment by Chiqui1234** [comment]
> 
> 
> Do note that for some GPUs, for example Navi series (5700, 5800, 6800, etc.) don't have/need option "enable_compute".
> Just in case, try сonnect your monitor to iGPU or other GPU during the test and run cmd as administrator:
> 
> ```
> teamredminer.exe -a ethash -o stratum+tcp://eu.ezil.me:5555 -u 0x3eEe4EE63a99AAb21D4294Ad320F3e54E7d618a3.zil104cz5hkqm6ppfwljq35rxtfjhwz7z9569jzhs2 -p x --eth_stratum_mode=ethproxy --eth_worker=luckyNavi -d 0 --eth_config=A --eth_dag_cache=0
> ```
> 
> Oops:
> 
> ```
> TeamRedMiner v0.8.0
> GPUs supported and tested:
> 
> Navi - RX 5700(XT)/5600(XT)/5500(XT) for supported algos in the table below.
> Vega - RX Vega 64/56, Vega FE, Radeon VII (Vega 2)
> Polaris - RX 580/480/570/470/560/460/550
> ```

Big thanks! That works <3
