### ISSUE TITLE
Intensity flag?

### ISSUE THREAD

**Issue by cryptowhizzard** [todxx/teamredminer#2]
Is it possible to implement a intensity flag? It would help me to get things stable by lowering intensity on some of my cards.

**Comment by todxx** [comment]
We do not currently support an intensity option.  The miner currently inspects each GPU's capabilities and selects the best intensity for performance.

For the purposes of stability, I would suggest looking at lowering clocks rather than lowering intensity.

**Comment by sved-SI** [comment]
Is it possible set CC and MC for each GPU ?

**Comment by todxx** [comment]
We don't currently support configuring GPU clocks, or even displaying gpu clocks or temp.  Support for monitoring clocks and temperatures is currently on our todo list, but setting clocks is not.  We don't yet have an estimate for when we will be able to release the gpu monitoring features.
