### ISSUE TITLE
Help Failed to list OpenCL platforms in Manjaro 20

### ISSUE THREAD

**Issue by keranapy** [todxx/teamredminer#206]
hello it presents me with the following error when executing the start_eth.sh in manjaro :
Team Red Miner version 0.8.1
[2021-02-06 18:53:10] Failed to list OpenCL platforms.
[2021-02-06 18:53:10] Successful clean shutdown.
I am using a Rx 5500 xt 8gb 

Could you guide me on how to solve it? Thanks in advance

**Comment by waytoroot** [comment]
you should to use amdgpu driver

**Comment by keranapy** [comment]
> you should to use amdgpu driver

yep Solved, thank you
