### ISSUE TITLE
Vega Frontier Edition is underperforming Vega 56 by ~8MH/s, both auto-tuned and with matching tunes.

### ISSUE THREAD

**Issue by appleguy** [todxx/teamredminer#217]
*Thank you* for your skilled software engineering on this project. If the code were open, I'd be interested in potentially helping!

That said, I've found that Vega Frontier Edition runs significantly slower in TeamRedMiner, even though in PhoenixMiner it runs at identical hashrate to Vega 56.

In my case:

- TeamRedMiner version 0.8.1, running on Linux kernel 5.4.80-hiveos
- Vega 56: Auto-tuning arrives at A454, achieving a stable 45.07 MH/s speed when heavily undervolted: Vcore=820mV, Core=1070Mhz, Mem=980Mhz. No other settings passed to TRM.
- Vega Frontier Edition:  Auto-tuning arrives at A512, but also setting A454 makes no real difference. 37-38 MH/s. Identical core and memory clocks. Can't break 40 even with higher clocks.

Neither card is throttling or running high temperatures, and the set clock frequencies are consistently reported by multiple tools.

PhoenixMiner is able to do 41.75 MH/s on the Vega Frontier Edition, and about 42 MH/s on the Vega 56. So TRM is a nice win for the Vega 56, but actually an even bigger regression for the Vega FE.

I've also tried the --eth_config=C in hopes of making use of the 16GB HBM2, but this dropped hashrates all the way to 4.7MH/s on the Vega FE. I've also tried --eth_config=B with no real improvement, still mid-30's MH/s.

Thanks for any investigation -- this does seem like some kind of bug or optimization opportunity, not just a technical question.

**Comment by supasnipa360** [comment]
I second this issue
