### ISSUE TITLE
Enable SSL/TLS for Mining Pool, (Dev pool can use port 443 ?)

### ISSUE THREAD

**Issue by MoneroChan** [todxx/teamredminer#22]
Hi, 
I notice that the Dev pool connects via port 443
Does that mean the dev pool is connecting over TLS/SSL? or is 443 just used by the dev pool to trick firewalls without SSL/TLS actually being used?

If so, is there anyway to similarly enable TLS/SSL for mining pools like supportXMR ?
I tried 443 with SupportXMR with teamredminer, but the pool instantly shuts down the connection.
443 works with other miners like XMRStak just fine with TLS enabled.

Thank you!

**Comment by repetenz** [comment]
Also interested in the answer to this, currently mining on port 80, but would much prefer TLS.

**Comment by todxx** [comment]
Just released version v0.4.0 with TLS/SSL support.
There are some bugs to iron out with dns redirects, so you must use the direct hostname of the pool server for ssl connections.

**Comment by MoneroChan** [comment]
Hi @todxx 
Thanks, 
- we're still getting : "Login Failed" error using stratum+ssl:// prefix
on SupportXMR 's pool , SSL/TLS port 9000  Direct to pool (Non-DNS Routed)

Example: "  teamredminer.exe -a cnr -o stratum+ssl://de01.supportxmr.com:9000 "
Result = Login Failed

Is SupportXMR pool only compatible with TLS (not SSL) ?

Thanks!

**Comment by todxx** [comment]
The SSL support includes TLS (actually I don't think it even supports the old/insecure SSL connections).

I know we saw issues with the hostname in the SSL certs not matching actual hostname with supportxmr, but we haven't had time to check what's happening in detail.  If you can run with something that captures/decodes the SSL negotiation process (such as wireshark) that will help to debug the issue.  Otherwise we will take a look at it when we can.  Right now we're fire fighting some other issues in the new release.

**Comment by MoneroChan** [comment]
Would you be able to paste a working example config for SSL for Supportxmr.com? I recall one of your donation wallets is on SupportXMR, Thank you! :)

**Comment by todxx** [comment]
I don't have a working config for SSL for supportxmr.com at the moment.  I know that SSL connections to nanopool did work though.

I will debug and sort out the issues with supportxmr.com SSL when I have a chance and let you know.

**Comment by todxx** [comment]
It appears that supportxmr's certificate does not actually have the correct server names in it.  We will disable server name checking for SSL connections in the next release.

**Comment by todxx** [comment]
SSL should now be fully functional with supportxmr in latest release.  Please re-open this issue if you have any other problems.
