### ISSUE TITLE
TRM Support for Cryptonight Waltz

### ISSUE THREAD

**Issue by ku4eto** [todxx/teamredminer#24]
Hello.

Is TRM going to support in the near future the upcoming Graft algorithm change?

https://www.graft.network/2019/01/23/nicehash-attacks-update/

**Comment by todxx** [comment]
Hey, we currently support graft's reverse waltz, so I'm closing this issue.  Please reopen if I got something incorrect.

**Comment by ku4eto** [comment]
Yup, it its an old request.
