### ISSUE TITLE
Please add support to AMD Radeon VII (gfx906)

### ISSUE THREAD

**Issue by Corpse666** [todxx/teamredminer#28]
Initialize error, unknown device name: 'gfx906'

**Comment by todxx** [comment]
There is initial support for Radeon VII (gfx906) in release v0.4.0.  We have not had time to do much testing, so it may be buggy.  We know that cryptonight perf is currently very low on the VII, and we will be addressing that in future releases.

**Comment by Corpse666** [comment]
Miner shows 4K, but real speed 2.5k. Very very low...

**Comment by todxx** [comment]
Can you try the latest version and post the output of the miner when you see this problem?

Generally speaking, we haven't optimized the miner for VII yet, so the 2.5kh/s number is not far from what one would expect.

**Comment by Corpse666** [comment]
Last miner version shows about 2.5-2.8K (SRB shows 3k) and its close to real pool speed. But the big difference with SRBminer is in terms of electrical energy consumption. TMR shows ~280w, SRB ~330w+- depends on wattman settings. And '--cn_config' don't to anything. "--cn_config 20+17" - also works as 15+15.

**Comment by Corpse666** [comment]
And i can't find any PPT settings/software for VII.

**Comment by todxx** [comment]
Currently I believe the best option for VII is 16+16 or 16-16.  I understand that our performance is below SRB currently, and we will be addressing it.  We've just been very busy lately with all the issues around adding new algorithms like CN/R

**Comment by Corpse666** [comment]
Do you have understands of any PPT groundwork (P states) for VII?

**Comment by todxx** [comment]
Sorry, I don't.  I only have one VII and it's on a linux machine, and even then I haven't spent much time tuning it.

**Comment by todxx** [comment]
This issue has been resolved in newer releases.
