### ISSUE TITLE
GPU 0 Warning: crossfire ulps is enabled in the registry. Use --enable_compute to fix. (RX 5500 XT)

### ISSUE THREAD

**Issue by bezyourself** [todxx/teamredminer#315]
I have this problem when running the TRM ver v0.8,2.1. My Radeon software or my GPUs don't have the --enable_compute toggle switch. So where do I get this error to resolve?

![182778941_926068118168298_2738368800694321574_n](https://user-images.githubusercontent.com/83681879/117088630-5f452a00-ad96-11eb-8c59-6204be7396fb.jpg)

**Comment by pdieppa** [comment]
The --enable_compute is used in the command line of TRM.

Example from the help section:

teamredminer.exe -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0x02197021fefa795fec661a45f60e47a6f6605281.trmtest -p x **--enable_compute**

**Comment by bezyourself** [comment]
Acknowledged, the issue has been resolved. But I have another problem with the hashrate too low when running this TRM program.
 
Thanks.
