### ISSUE TITLE
GPU tuning by TRM

### ISSUE THREAD

**Issue by BetaVersionBY** [todxx/teamredminer#324]
Will it be possible to tune the GPU's clock and voltage using TRM?

**Comment by pdieppa** [comment]
Currently I don't believe TRM supports it. If you run Windows and use Afterburner, there is a way you can run Afterburner from the command line right before running TRM. This ensures TRM always runs with the correct OC setting applied.

**Comment by BetaVersionBY** [comment]
> 
> 
> Currently I don't believe TRM supports it. If you run Windows and use Afterburner, there is a way you can run Afterburner from the command line right before running TRM. This ensures TRM always runs with the correct OC setting applied.

Sometimes while mining my videodriver freezes and reboots and Afterburner drops all settings to stock and mining proceeds on stock settings, which is unacceptable. This is why i need TRM to be able to manage GPU's setting by itself.

**Comment by pdieppa** [comment]
That's why I mentioned you can run Afterburner from the command line and apply any of the profiles automatically. You can edit your TRM batch file and include the command line for Afterburner before TRM runs.
