### ISSUE TITLE
Autolycos Vega 56

### ISSUE THREAD

**Issue by dyvimtarkan** [todxx/teamredminer#327]
Hi
I have a Win 10 - System with 4x Vega 56. ETH-mining with 4 card works great.
Now I tested Ergo-mining (autolykos2) and Teamredminer 8.3 states Error -31 for the fourth card (Device 3 does not initialise...).

I tried to split the miner-start, cards 0,1,2 together work fine with Ergo.
Single start for card 3 still fails with error 31.
Any idea?
Addition:
I tried to start ETH-Mining on card 3 again (whilest the other cards mine Ergo) - this works!
So there seems to be an issue with using/initialising more than 3 cards for autolycos2.

Regards,
Andre

**Comment by peternord71** [comment]
Have almost the same issue
Have been mining on srbminer without trouble.
Thought I should try teamredminer to get higher hashrate. When I try to start trm I get
GPU3 Failed to initialize (-31).

Tried one gpu at the time, no problem.
Tried two gpus in different combinations, no problem.
Tried three gpus i different combinations, no problem.

But as soon as I try four or five I get the Failed initialize error.

Anyone know the issue and how to fix it?

**Comment by peternord71** [comment]
Solved it, had to manually set win10 virtual memory to 36 Gb

**Comment by dyvimtarkan** [comment]
Superb, thx!
I tried it with 32 GB virtual mem and it was enough, Autolycos on all four cards works!
