### ISSUE TITLE
Please Hash Verify Releases? (MD5, SHA256 Hash check) 

### ISSUE THREAD

**Issue by MoneroChan** [todxx/teamredminer#33]
Hi @todxx, thanks for your good work, 
i'm wondering if you can please provide verification hashes your releases? 
It's very important because it's closed sourced code.

teamredminer-v0.4.2-win.zip
SHA256 : 35A36F24A3F2478A70D86FA33484FF1752060829BAFD1FF11C1ED4211BE33D9A
MD5 : E8BECBDAA37FE8108777CFE53523F9E0

Is this correct?

Thanks!

**Comment by todxx** [comment]
That is correct, the sha256sum is: 
35a36f24a3f2478a70d86fa33484ff1752060829bafd1ff11c1ed4211be33d9a
