### ISSUE TITLE
Miner doesn't start, no error reported

### ISSUE THREAD

**Issue by baduhai** [todxx/teamredminer#341]
I'm on linux, I've tried using both ROCm as well as amdgpu-pro on my rx580, but neither work. The output is simply the following:

```
          Team Red Miner version 0.8.3
[2021-05-31 14:26:32] Auto-detected AMD OpenCL platform 0
[2021-05-31 14:26:32] Successful clean shutdown.
```

The command I'm using to run the script is `teamredminer --debug -a ethash -o <pool-address> -u <wallet> --eth_worker <worker-name> --eth_aggr_mode`. (Of course, replacing the <> with the relevant info.)

What's weirdest, is that the miner was functioning perfectly fine up until a few days ago. I check my package manager logs to see if an update to the drivers could have caused this, but while there was an update recently, I used the miner with no issue after that update. Other miners still work, I'm currently using nsfminer, but none of the miners I've tested reach the same hashrate that TRM does.

**Comment by baduhai** [comment]
Recent update to drivers changed permissions somewhere. Not entirely sure how to fix, but a workaround is running TRM as sudo.

**Comment by luncht1me** [comment]
Seems latest ROCM 4.2 doesn't work, perhaps another parsing error w/ the latest update?

**Comment by Campincooper** [comment]
😋 thanks
