### ISSUE TITLE
Ubuntu 20.04.2: Failed to list OpenCL platforms

### ISSUE THREAD

**Issue by daxime** [todxx/teamredminer#343]
Hi,
i have a issue with TeamRedMiner. He tell me "Failed to list OpenCL platforms".

I have followed this step to install ROCm on my Ubuntu 20.04.2: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

At the end, these two commands don't work:
/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo

But if i run them with sudo, both work well. I tried with Blender, without sudo he doesn't see my GPU, but with sudo it work fine. Same with XMRig.

So i tried with TeamRedMiner, but even with sudo, it say "Failed to list OpenCL platforms" ...

what can i do to solve this problem?

OS : Ubuntu 20.04.2 (fresh install and up to date)
Kernel : 5.8.0-53-generic
CPU : Ryzen 2600
GPU : 5500 XT (8Gb)
RAM : 16Gb

**Comment by torinedge** [comment]
Try AMD's ROCR driver... https://amdgpu-install.readthedocs.io/en/latest/install-installing.html

**Comment by daxime** [comment]
Already tried. After the installation of that, Gnome don't launch any more ... Tired the "pro" install, Gnome work, but not OpenCL ...

**Comment by daxime** [comment]
NSFMiner work fine. I'll wait for a fix (if the issue is from TRM), and try again later.

**Comment by SandboChang** [comment]
I got Teamredminer to work after trying a couple hours. Somehow I never got it work by using the ROCm stack; I needed to use amdgpu-pro driver.

I followed this page:
https://www.blog.albertbling.com/posts/how-to-mine-ethereum-on-linux/

When installing the Pro drivers, I had a couple errors related to dkpg unable to overwrite stuff. It will split out what they are, and you can then force it by
`sudo dpkg -i --force-overwrite <package location>`

I needed to do this twice, but finally it still gave my the error related to amdgpu-dkms. Nonetheless I tried to run teamredminer, to my surprise it actually works.

**Comment by gutteronion** [comment]
I know this is a bit late, but I figured that I would provide what I did to get teamredminer working. First of all, this worked for me using the open-source linux drivers, not the official AMDGPU PRO drivers. 

Secondly, I did this on MANJARO. I grabbed this package from the AUR:
[https://aur.archlinux.org/packages/opencl-amd/](url)

(I believe it is a .deb package to begin with, so it should be in the ubuntu/debian repos). Anyways, I found a package called "opencl-amd". This installs the official opencl files that the miner is calling for, and it works alongside the free open source AMDGPU drivers.

As, I have rarely used debian/Ubuntu, I do not know how to install this package. Please do your best to make informed decisions, and take careful steps using the information I provided if your are unfamiliar with linux.
