### ISSUE TITLE
API

### ISSUE THREAD

**Issue by xscxscxsc** [todxx/teamredminer#35]
hi guys
I set api, but unable to monitor on another computer.
teamredminer.exe -a cnv8_rwz -o stratum+tcp://graft.miner.rocks:5005 -u abcd --api_listen=0.0.0.0:12345

example --api_listen=127.0.0.1:12345  or 127.0.0.1:4028 or 0.0.0.0:4028
I've tried them all. I can't monitor them. 
Please help me. How should I set it? Thanks.

**Comment by todxx** [comment]
Hi,

Can you explain a little more by what isn't working?  What happens when you try to monitor the miner?  Does the miner print that it has started the API when you run it?

What tool are you using to monitor the miner?  Can you try using AwesomeMiner and see if that works?

**Comment by xscxscxsc** [comment]
Hi

Thanks for your reply.
This is other SRB Miner. Input IP and port, The following screen will appear.
[cid:5e18e79a-b636-4bf9-91e4-362053e3eb2d]
Start.bat
[cid:43e0e691-c4ff-424f-af3a-bd1620c60d94]

But I use teamredminer-v0.4.2-win. Unable to input IP and port for monitoring.
Start.bat
[cid:a7fd0937-d6e3-4907-820c-b78f646ffb4b]

[cid:497e7614-72f0-4837-969a-7cada3e7ae28]
[cid:64403984-db75-4113-ad2b-0321face08c3]
Please help me, Thanks again.

By the way, I use teamredminer v0.4.2 run Graft or XMR for a period of time(4-6hours), system is restart. But I use SRBminer run Graft or XMR for a few days is Working properly. I don't know what went wrong.


________________________________
发件人: todxx <notifications@github.com>
发送时间: 2019年3月16日 14:14
收件人: todxx/teamredminer
抄送: xscxscxsc; Author
主题: Re: [todxx/teamredminer] API (#35)


Hi,

Can you explain a little more by what isn't working? What happens when you try to monitor the miner? Does the miner print that it has started the API when you run it?

What tool are you using to monitor the miner? Can you try using AwesomeMiner and see if that works?

―

**Comment by todxx** [comment]
The images you posted did not show up.  Can you repost them via github so they will show up?

As for stability, different miners and algos will behave differently.  You may need to adjust your clocks and/or voltages to run stable in TRM as compared to SRB.  That said, usually GPUs will just crash and stop hashing, they don't usually restart the system.  Do you have a log of what happened?

**Comment by xscxscxsc** [comment]
Hi

Thanks for your reply.
This is other SRB Miner. Input IP and port, The following screen will appear.
![image](https://user-images.githubusercontent.com/35574081/54474596-c6ec3400-4821-11e9-9bc4-d48c987516d8.png)
Start.bat
![image](https://user-images.githubusercontent.com/35574081/54474598-d1a6c900-4821-11e9-9f17-cd889bf1f304.png)
But I use teamredminer-v0.4.2-win. Unable to input IP and port for monitoring.
Start.bat
![image](https://user-images.githubusercontent.com/35574081/54474602-e08d7b80-4821-11e9-99ca-7b50a8082190.png)
![image](https://user-images.githubusercontent.com/35574081/54474605-e7b48980-4821-11e9-804f-b4274312832a.png)
![image](https://user-images.githubusercontent.com/35574081/54474609-eedb9780-4821-11e9-845f-abf534c3a15b.png)



Please help me, Thanks again.

By the way, I use teamredminer v0.4.2 run Graft or XMR for a period of time(4-6hours), system is restart. But I use SRBminer run Graft or XMR for a few days is Working properly. I don't know what went wrong.

**Comment by todxx** [comment]
It seems there is some confusion about the API.  Our API is implemented following the sgminer API protocol.  It is not a web-based api unfortunately.  In order to access the API you will need to either write your own scripts, or use a tool like AwesomeMiner that has support for the API interface.

**Comment by xscxscxsc** [comment]
OK I know.

**Comment by xscxscxsc** [comment]
I will enable log, when system is restart, I send you it. Please check it, thanks.

**Comment by xscxscxsc** [comment]
[log.txt](https://github.com/todxx/teamredminer/files/2974020/log.txt)
Please check it , thanks

**Comment by ku4eto** [comment]
> 
> 
> The images you posted did not show up. Can you repost them via github so they will show up?
> 
> As for stability, different miners and algos will behave differently. You may need to adjust your clocks and/or voltages to run stable in TRM as compared to SRB. That said, usually GPUs will just crash and stop hashing, they don't usually restart the system. Do you have a log of what happened?

Actually, i can confirm, that if there is instability (either core voltage or strap/memory clocks), it will reboot on Windows. Not a big deal, i actually find it better this way. Prevents BSOD or hardfreeze lockups.

**Comment by todxx** [comment]
Closing old issue.  If you're still having these problems with the newer releases, please open a new issue.
