### ISSUE TITLE
Support Bitcore(Timetravel10) algo

### ISSUE THREAD

**Issue by kr1z1s** [todxx/teamredminer#36]
VERY LOW hashrate on NEW Vega cards with sgminer - https://github.com/bitbandi/sgminer-timetravel

My Vega64 hashrate - 18 Mh. At the same time, it is not loaded at all.

Please add kernel for Bitmark(Timetravel10)

Know CL files
[time10.zip](https://github.com/todxx/teamredminer/files/2973583/time10.zip)

**Comment by todxx** [comment]
Sorry, but we do not currently plan to add timetravel10.  There are many algos out there, and we don't have the resources to add all of them unfortunately.
