### ISSUE TITLE
Any plan to fix the issue that cannot read mem temp for RX6000?

### ISSUE THREAD

**Issue by fgg1991** [todxx/teamredminer#361]
I am using 6800xt, and I know only HWINFO can provide gpu memory temperature for now, even gpuz or aida64 cannot do it for 6800 or 6900.

Is any chance to give teamredminer a update help it to read the mem temp correctly?

**Comment by Kerney666** [comment]
Like I just replied in a similar issue, it's a bit of a research project getting it working. After all, it's core business for HWiNFO64 to pull it off using (my assumption) a hack that pokes the gpu's registers directly to probe for the mem temp over its i2c bus, it also needs Administrator access.

So, we'll see if we get around to it, I've honestly just been waiting for AMD to get their sh*t together and expose the sensor, I can't think of a single good reason for exposing it on linux but skipping it for windows. That doesn't seem to happen though, so we might need to reconsider.
