### ISSUE TITLE
Three 5700XT can only run two

### ISSUE THREAD

**Issue by myckjx** [todxx/teamredminer#364]
Three 5700XT can only run two.  But it all works when using lolminer.  This is an inexplicable trouble!
System: Windows10
Teamredminer:0.8.3
Driver: AMD official driver
Others: The firewall of wimdows is turned off, and the anti-virus software is not installed.and there is no overclocking.

**Comment by Kerney666** [comment]
Not providing much info, but my guess is you need to increase your virtual memory size in Windows. We use more vram than lolminer, and all allocations in windows need to be backed by host-side memory.

Make sure your virtual memory configuration is set to a custom size of at least 25000MB and try again. Reopen if still an issue.
