### ISSUE TITLE
Failed to initialize device idx 0 on TRM 0.8.3 with 21.6.1

### ISSUE THREAD

**Issue by MVasquezCL** [todxx/teamredminer#367]
On launch it gives a "failed to initialize device idx 0" (just like with some previous releases). Reverting back to 21.5.2 fixes the issue.

**Comment by Nickatron** [comment]
Referring to the new AMD driver, 21.6.1. 
Same issue here though.

**Comment by sorasoras** [comment]
same issue as well.

**Comment by batteryaziz** [comment]
Same issue with latest 21.6.1 driver, 21.5.2 works correctly (6700 XT).

**Comment by jarmandoh** [comment]
Same issue with latest 21.6.1 driver (FidelityFx Super Resolution API implementation), 21.5.2 works correctly (5500 XT).

**Comment by jimiche** [comment]
Same issue here with rx 6700 xt under 21.6.1 drivers.

I've moved to phoenixminer using generic kernel as I wait for a solution.
Default kernel at phoenixminer, and lolMiner are actually having same issue as Team Red Miner.

Thanks

**Comment by voodoopant** [comment]
Same here . Vega 56 .

**Comment by li-st** [comment]
Same issue here.
rx 6700xt with 21.61. drivers.

**Comment by Xitrapharlax** [comment]
Same issue, 6700XT

**Comment by liels** [comment]
Same here; trying to move from windows to linux / Ubuntu and ran into this.  Single 5600 XT also used for the display (screen).  20.04 and amdgpu-pro 21.10

**Comment by StioF80** [comment]
Same issue failed to initialize device idx 0 for optional release driver 21.6.2

**Comment by Cake-Chaser** [comment]
same here

**Comment by gongdao123** [comment]
Same issue here.

**Comment by runbox13** [comment]
Same issue here with 21.6.1 and 21.6.2 drivers (rx 6700xt)

**Comment by Qiz4i** [comment]
Boys,I reverted to 21.5.2 and it works flawlessly, i hoppe we will get an update on the miner for new drivers.

**Comment by m0haz** [comment]
When will they release an update to fix this??? Wanna take Dev fees, I don't mind at all as long as YOU STAY UP TO DATE!! WHERE ARE MY FEES GOING HMM??

**Comment by Vasmar93** [comment]
> When will they release an update to fix this??? Wanna take Dev fees, I don't mind at all as long as YOU STAY UP TO DATE!! WHERE ARE MY FEES GOING HMM??

I agree. This isn't a free program and it's been two weeks already without getting any sort of update.

**Comment by jessloc** [comment]
I'm having the same issue, reverted to 21.5.2

**Comment by heavyarms2112** [comment]
New drivers aren't yet supported. Don't upgrade to 21.6.1 versions.

**Comment by Liger0** [comment]
I use 21.6.1 on a vega 56 with no issue.

**Comment by Vasmar93** [comment]
> New drivers aren't yet supported. Don't upgrade to 21.6 version.

How is this comment useful to anyone? You're stating something that's pretty obvious and also the reason why the ticket exists.

**Comment by jimiche** [comment]
gminer is working pretty well with newest drivers

**Comment by Meguminrt** [comment]
Привет.
Обновлен драйвер AMD до 21.6.1.
Видеокарта amd radeon VII.
майнер выдает ошибку и не работает.
Ошибка: не удалось инициализировать идентификатор устройства 0 (-13)

**Comment by batteryaziz** [comment]
Solved for me in 0.8.4

**Comment by MVasquezCL** [comment]
Fixed in 0.8.4.

**Comment by Cake-Chaser** [comment]
Still dosent work for me.
I am in 21.6.2 with a radeon vii
