### ISSUE TITLE
 Initialization failures 

### ISSUE THREAD

**Issue by ftsguy** [todxx/teamredminer#37]
Not sure if it's my machine or not but version 4.2 seems to be freezing my machines more often on initialization than 4.1 was. On win 10.

**Comment by ftsguy** [comment]
Running rx 550s

**Comment by todxx** [comment]
Issues during the initialization phase can often be due to bad risers.  Please make sure that you are running the PCIe slots in gen1 or gen2 mode if you can.

**Comment by ftsguy** [comment]
Yeah issue went away applogiesfor the lack of detail. I have another  issue on linux with the program locking up after a GPU failure I'll post details later tonight.
