### ISSUE TITLE
AMD Radeon 21.6.x drivers still incompatible with TRM 0.8.4 Vega 56

### ISSUE THREAD

**Issue by 9dagothur9** [todxx/teamredminer#382]
Error: Failed to initialize device idx 0 (-13)
still works with 21.5.2
Vega 56

**Comment by colind88** [comment]
+1

**Comment by echodreamz** [comment]
+1, no go here.

**Comment by Kerney666** [comment]
Curious, do you run your Vegas with HBCC enabled (Radeon software -> Settings -> Graphics -> Advanced)? I do not have any issues on recent drivers on a Vega 56, but there are initialization issues if I turn on HBCC.
