### ISSUE TITLE
Change eth_config parameter while miner is running.

### ISSUE THREAD

**Issue by pomputer** [todxx/teamredminer#383]
Hi!
Is there any way of changing the `eth_config` parameter without restarting the miner, preferably through an API?
Thank you!

**Comment by Kerney666** [comment]
Not today, but has been discussed a few times. I think it's a good feature, we can add it both through a command line fine tuning menu option like we used to have for Cryptonight algos, and also add a custom API call through the sgminer api, i.e. just a plain tcp/ip socket that writes either a text or a json snippet.
