### ISSUE TITLE
Miners can't mine Binance mining pool

### ISSUE THREAD

**Issue by adaptor2006** [todxx/teamredminer#387]
Why can't teamredminer mine the Binance mining pool?
It will shut down when it is set to start

**Comment by 9dagothur9** [comment]
It can mine on Binance. What settings u use?

**Comment by K1LL3RPUNCH** [comment]
Yeah, samething here

**Comment by K1LL3RPUNCH** [comment]
> 
> 
> It can mine on Binance. What settings u use?

teamredminer -a ethash -oethash.poolbinance.com:8888 -u !accountname! -p x --eth_worker !F1!

**Comment by adaptor2006** [comment]
I'm stuck here
![1628804254214](https://user-images.githubusercontent.com/51144663/129273531-22c4c5e0-ce70-4a76-8631-3cc8c9189b77.jpeg)

**Comment by 9dagothur9** [comment]
teamredminer -a ethash -o stratum+tcp://ethash.poolbinance.com:3333 -u "Yourusername" -p x --eth_worker "Yourworker" --eth_config="See what autotune gives you then enter the value here"

Also disable ULPS, it's in the TRM folder, and restart computer.

**Comment by adaptor2006** [comment]
I found the reason
I turn off the IPS of the ASUS router
intercept
You can mine

**Comment by K1LL3RPUNCH** [comment]
> 
> 
> teamredminer -a ethash -o stratum+tcp://ethash.poolbinance.com:3333 -u "Yourusername" -p x --eth_worker "Yourworker" --eth_config="See what autotune gives you then enter the value here"
> 
> Also disable ULPS(enable compute) , it's in the TRM folder, and restart computer.

this worked for me, thx c:

**Comment by Kerney666** [comment]
Closing.
