### ISSUE TITLE
nr_cu_overide = can someone explain tha dvantages for this command?

### ISSUE THREAD

**Issue by dvirmail** [todxx/teamredminer#390]
Hi guys,
I have vega 64s flashed to 56
I'm tryind to understand the benefits of the nr_cu_overide command, 
I've added the command and changed the cu to 64 for all my vegas but seen no diffrenece in the hashrate, should it make any differnece?
Thanks

**Comment by Kerney666** [comment]
The argument was added to help with some testing in rare corner case situations, it won't make a difference in your case.
