### ISSUE TITLE
Radeon VII crashes almost immediately opon opening TRM

### ISSUE THREAD

**Issue by Velocity535** [todxx/teamredminer#391]
This has never been a problem before. I shut down my computer to dust it out and upon turning it on I get this error message: "Failed to initialize device idx 0 (-13)", then the miner closes completely.

I have to resort to other miners for the time being, sucks cause the are no where as efficient as TRM

If you could look into this issue and offer a solution I would be extremely grateful.

Thanks
![Screenshot_20210814-123144_Gallery](https://user-images.githubusercontent.com/86106921/129453075-ecd0551b-0912-401c-9e75-c04047adf4ec.png)

**Comment by echodreamz** [comment]
It's been reported a few times.

**Comment by colind88** [comment]
LOL miner is your friend until they get this sorted - Radeon VII owner here with exactly the same issue!!

**Comment by Kerney666** [comment]
We know about this, you can downgrade to an earlier driver or wait for a patch. The main issue is that AMD implemented much stricter checks of precompiled binaries in later driver versions and are now rejecting binaries that earlier drivers accepted. 

Should be solved in 0.8.6 (0.8.5 is just about to go out). Closing this ticket, please follow dup issues for more info.
