### ISSUE TITLE
No difficulty shown in autolycos2

### ISSUE THREAD

**Issue by nunziolop** [todxx/teamredminer#395]
When mining autolycos2 there is no diff reported of the found share.
Is there a way to report the diff of the submitted share?
That would be useful in a solo mining pool to cross check if you have found a valid share yo mine the block.

**Comment by damachine** [comment]
mee too

**Comment by Kerney666** [comment]
Duplicate, even if we're sloppy to provide feedback here at times, please only submit one ticket.
