### ISSUE TITLE
Dev pool failed to connect. HELP

### ISSUE THREAD

**Issue by damachine** [todxx/teamredminer#397]
Hello since today this message comes:
Dev pool failed to connect.
Mining will proceed at reduced rate while not connected to dev pool.

I`m on Hiveos with trm v 0.8.4 i had nothing change in my network to block ports or else. 

Thanks all

**Comment by Kerney666** [comment]
If this is intermittent and you see a log line "Dev pool connected and ready." 5-10 secs later, you can totally ignore it. If you always see it, over and over again, it's a problem though. If you still have this issue, please reopen the ticket.
