### ISSUE TITLE
GPU 7 Failed to initialize device (-31)

### ISSUE THREAD

**Issue by ToyYan** [todxx/teamredminer#398]
I have a vega56 mining machine with 8 cards. If I enable the first 7 cards, it will mine normally. If all of them are enabled, an error will be reported.

> C:\qskg\exts\teamredminer-0_8_4>"teamredminer.exe" -a autolykos2 -o stratum+tcp://ergo.666pool.cn:9556 -u ysssss.01 --log_file="C:\qskg\log\20210820_104914_ERGO_log.txt" --api_listen=0.0.0.0:4068 --cm_api_listen=0.0.0.0:3333 --enable_compute -p x
>           Team Red Miner version 0.8.4
> [2021-08-20 10:56:25] Running in administrator mode.
> [2021-08-20 10:56:28] Auto-detected AMD OpenCL platform 0
> [2021-08-20 10:56:31] Initializing GPU 0.
> [2021-08-20 10:56:31] Initializing GPU 1.
> [2021-08-20 10:56:31] Initializing GPU 2.
> [2021-08-20 10:56:32] Initializing GPU 3.
> [2021-08-20 10:56:32] Initializing GPU 4.
> [2021-08-20 10:56:33] Initializing GPU 5.
> [2021-08-20 10:56:33] Initializing GPU 6.
> [2021-08-20 10:56:33] Initializing GPU 7.
> [2021-08-20 10:56:34] GPU 0 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 1 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 2 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 3 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 4 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 5 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 6 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:34] GPU 7 Passed compute mode and crossfire verification.
> [2021-08-20 10:56:35] GPU 7 Failed to initialize device (-31)
> [2021-08-20 10:56:37] Successful clean shutdown.

**Comment by Kerney666** [comment]
You don't have enough virtual memory defined in Windows. Increase it +8192MB or something and you will be good. 

Windows is annoying in that all allocated gpu buffers in vram must be backed by host-side memory. It's fine if that memory is swap space (virtual memory) though, hence the reason for big rigs needing massive amounts of virtual memory defined.

Reopen if still an issue.
