### ISSUE TITLE
Worker name turned into _default_ when there's a network break or similar problem

### ISSUE THREAD

**Issue by MollyZhang1** [todxx/teamredminer#400]
Normal status:
miner setting
0xhdgdgsdshdjsg7383333.001
0xhdgdgsdshdjsg7383333.002
0xhdgdgsdshdjsg7383333.003
Pool shows workers as
001
002
003

After network break or similar problem,
miner setting(unchanged)
0xhdgdgsdshdjsg7383333.001
0xhdgdgsdshdjsg7383333.002
0xhdgdgsdshdjsg7383333.003
BUT POOL SHOWS WORKERS AS
_default_    hashrate being the sum of 001 002 003

In FlintOS, they may ask clients to manually add this setting to solve the problem
eth_stratum_mode=ethproxy
In other OS, there's also the problem
Please help solve the problem.
Thanks.

**Comment by Kerney666** [comment]
Continued discussion on Discord, closing here.
