### ISSUE TITLE
Possibility switch back main pool from failover pool when it resume?

### ISSUE THREAD

**Issue by shamashii** [todxx/teamredminer#401]
teamredminer.exe -a autolykos2 -o stratum+tcp://failoverpool -o stratum+tcp://mainpool -u walletaddress -p pw --enable_compute

Failover pool worked when main pool down, but it seems not switch back when main pool come back, how to do it?

**Comment by Kerney666** [comment]
You have the pools in the wrong order. The main pool must come first to get priority. Over time, it should switch back automatically to the first active pool in the list. You might have provided a truncated argument list above, not sure, but you also need a full pool specification for the failover pool with a user and password.
