### ISSUE TITLE
RVN/ZIL on 4GB Cards Not working

### ISSUE THREAD

**Issue by isbrodie1** [todxx/teamredminer#402]
Hi Team, 
Looks like 4G cards are not dorking for dual mining RVN and ZIL, its working fine with my 5700xt rig, but not by rx570 4gb rig.
Would be awesome if this was in the next update, should be ok as the DAG for RVN is well below 4GB

**Comment by Kerney666** [comment]
To avoid rebuilding the DAGs for kawpow and ZIL the two algos currently run their own buffer(s). Kawpow is close to 3GiB, and ZIL is always 1GiB, then add some aux buffers and 4GiB isn't enough. It needs some work to share buffers and only partially borrow space from kawpow to fully fit the ZIL dag, rebuilding both full DAGs on every switch isn't great.

In short, we'll return to this in a bit, have some more pressing TODO items to handle first.

**Comment by isbrodie1** [comment]
Thanks for the update, it makes sense now. 
I've switched to ETC/ZIL and no issues with that.
