### ISSUE TITLE
Ethash mode B not supported

### ISSUE THREAD

**Issue by Kooza25** [todxx/teamredminer#404]
Hello there, I'm using an RX580 Aorus 8gb
I get the error that mode B is not supported with drivers that doesn't allow large allocations, switching to mode A.
I've tweaked with the one click Polaris and getting only 7mh

**Comment by DeeDeeRanged** [comment]
Windows/Linux?

**Comment by Kooza25** [comment]
Sorry I forgot this, it was a gpu driver issue, not miner related. Thanks!
