### ISSUE TITLE
Suggestion: Minimum total hashrate watchdog

### ISSUE THREAD

**Issue by AlirezaXdehghan** [todxx/teamredminer#408]
TRM rocks, but one thing that's missing is watching hashrate for all cards
currently trm only watches the hashrate per card which suffices in many cases, but specifying a minimum total hashrate lets the miner know if one or more gpu has not been initialized when booting and the system needs a restart.
for example I know my rig hashes around 200mh/s and if it falls below 170, one of the cards surely has not been initialized.
I hope you'd consider adding this feature.

**Comment by Kerney666** [comment]
It's simple and a reasonable feature. I've added it to our TODO list, will probably appear in 0.8.7. Closing for now.
