### ISSUE TITLE
How can i gameon one GPU and mine with the other on team red?

### ISSUE THREAD

**Issue by Schmitty471** [todxx/teamredminer#411]
I dont know how to stop 1 gpu from mining and keep the other one mining? if anyone know it would really help thanks!

**Comment by CPTEliteBussy** [comment]
Add this into your batch file just after where it says -a *algorithm* -d 0,1,2,3

Only use the number corresponding to your gpu. Your first gpu will be labelled as 0 so if you want to use that for mining add -d 0.

Watch your miner to see which gpu is active. Sometimes even though my main gpu is in slot “0” it identifies to the miner as gpu 1. So if -d 0 doesn’t select the right one change it to -d 1 and so on until you select the right one.

**Comment by Schmitty471** [comment]
Thanks!

**Comment by CPTEliteBussy** [comment]
Add this into your batch file just after where it says -a *algorithm* -d 0,1,2,3

Only use the number corresponding to your gpu. Your first gpu will be labelled as 0 so if you want to use that for mining add -d 0.

Watch your miner to see which gpu is active. Sometimes even though my main gpu is in slot “0” it identifies to the miner as gpu 1. So if -d 0 doesn’t select the right one change it to -d 1 and so on until you select the right one.

**Comment by CPTEliteBussy** [comment]
Cheers man glad I was able to help. Happy mining!
