### ISSUE TITLE
Help needed on hiveos with trm dual mining

### ISSUE THREAD

**Issue by nottiadn** [todxx/teamredminer#412]
I'm having issue configuring trm with hiveos.

On single mining eth everything looks OK. But when I added zil to do dual mining, it starts showing the error

Invalid rpc id received.

I am running on 8 x 6600xt on hiveos

How do I fix this? Anyone kind to share your settings for trm on hiveos with ethermine pool and ezil?

**Comment by Kerney666** [comment]
Please join our discord, go the the #zil-dualmining channel and tag @support with your question and they'll help you set it up. There will be a bunch of working examples in the channel history as well. 

Discord link: https://discord.gg/RGykKqB

Closing.
