### ISSUE TITLE
ETH hashrate fluctuates with RX 6900 XT when using --clk params

### ISSUE THREAD

**Issue by merlin2222** [todxx/teamredminer#413]
Hello,

this is the command I'm using to start the miner (v0.8.5):

teamredminer.exe --clk_core_mhz=1450 --clk_core_mv=850 --clk_mem_mhz=2140 --clk_timing=1 --fan_control=60::80:35 --eth_config=A1152 -a ethash -o stratum+tcp://eth-eu.sparkpool.com:3333 ...

Miner is showing correct values for core clock and mem clock params.  VDDC is shown to be 800mV. Fan control works fine.

Hashrate fluctuates, together with power, with every shown stat roughly between 30Ms/s and 90W and  62Mh/s and 148W. 

I'm using Windows driver 27.20.14540.8001. The same happens with newest AMD driver.(radeon-software-adrenalin-2020-21.6.1-win10-64bit-june28).

I can get card to mine at stable 63Mh/s with AMD utility but after a few hours it ends up with error "driver time-out" or something, so I installed only AMD driver and start using --clk params to set OC and then I faced this hashrate fluctuation issue. I tried swithing to Microsoft driver, but same thing, so I'm kindly asking for help.

Best regards,
Kruno

**Comment by CPTEliteBussy** [comment]
If you’re using a 6600XT then your only option for TRM is the new 0.8.5

swap back to 0.8.4 or another previous version until 0.8.6 comes out.

**Comment by CPTEliteBussy** [comment]
I’m also assuming your memory clock is too high. My 6800XT’s only like 2075 mem. But go back to a previous version. Check your clocks. Do a little testing yourself. I always keep older versions of drivers /software so I can play around. I don’t have a 6900XT as of yet so I can’t really say I know for sure.

**Comment by merlin2222** [comment]
Oddly enough, after 4 hours of mining hashrate stabilised at 63Mh/s. I restarted the miner and same thing happened - hashrate fluctuated for app 3-4 hours and then settled at 63Mh/s.

Memory clock is fine as there are no rejected shares and temps are ok.

**Comment by merlin2222** [comment]
After app 90 min of happy mining hashrate and power fluctuations are back again. 

Temps are stable all the time which indicates card is not thermal throttling.
