### ISSUE TITLE
Dev pool connected failed

### ISSUE THREAD

**Issue by mickeyandkaka** [todxx/teamredminer#417]
https://github.com/todxx/teamredminer/issues/17

have the same problem with it. However I can access google and teamredminer.info  from china. 
And wonder what's your ip of dev pool?

**Comment by Kerney666** [comment]
teamredminer.info is not a sanctioned website, we know about it and will probably launch our own site, please download directly from github, although I believe that site still link there. 

We have a number of mainland China servers, a VPN shouldn't be necessary, but it depends on what IP you're providing for geo dns resolution. The IPs for your location should be returned when you do a dns lookup for dev2.teamredminer.com.

**Comment by mickeyandkaka** [comment]
Successfully solve it using google dns. Seems the domain was blocked in china.

**Comment by Kerney666** [comment]
Closing.

**Comment by 1064298219** [comment]
> 使用google dns成功解决。好像这个域名在中国被屏蔽了。

请问是如何解决的？ 更改以太网DNS吗？
