### ISSUE TITLE
Please add Octopus algo

### ISSUE THREAD

**Issue by rhyno78** [todxx/teamredminer#418]
Please add Octopus algo to teamredminer… so far this is the only algo that unmineable on AMD GPUs.. Thank you

**Comment by alorbach** [comment]
That would be awesome if Octopus could be added ASAP.

**Comment by Kerney666** [comment]
Even with an absolute best in class implementation of Octopus on AMD, it won't stand a chance against the Nvidia RTX gpus with tensor cores. The algorithm is more or less created for doing the type of matrix multiplication that the tensor cores provide direct hardware support for. It's very hard to see a case where direct mining Conflux on AMD is better than mining eth and buying cfx instead. Closing.
