### ISSUE TITLE
please, add support for cryptonight-ryo ! thanks you !

### ISSUE THREAD

**Issue by lamgztey** [todxx/teamredminer#42]
Hi, would it be possible to add support for cryptonight-ryo !
https://miningpoolstats.stream/ryo
https://ryo-currency.com/
https://github.com/ryo-currency/ryo-currency
https://discord.gg/ryD9bdb
https://www.coingecko.com/en/coins/ryo

**Comment by todxx** [comment]
Sorry, but we do not currently plan to support cryptonight-ryo or the cn-gpu algo.
