### ISSUE TITLE
Trm keeps resetting whenever I reboot/power on

### ISSUE THREAD

**Issue by darkgodbm** [todxx/teamredminer#424]
I have a hiveos rig with 6 5700 XT. They can run for days/weeks long without any issue, but if for whatever reason I have to reboot the rig (like updating hive, or maybe a power shortage, let's say) it will keep resetting every few minutes with a gpu dead message (the gpu itself is random). 

The only way I have to stop it from doing this is pausing the miner as soon as the rig boots, changing WHATEVER setting in the card, like voltage or so, and just changing it back and restarting the miner.

Anyone have ANY idea what causes this? It does not happen to other miners, but either I get higher power consumption with them and mostly lower shares, too, so I really didn't want to change.

**Comment by darkgodbm** [comment]
> This isn't a miner issue per se, it's simply out of scope for the layers that we interact with (primarily OpenCL), although I'm not disputing that TRM might be triggering the issue and others miners not (for some reason). I'd say it's pretty normal with a double reboot, the first reboot ending up with e.g. the SMU in one or more gpus in a weird state, but not an endless cycle of reboots, can't say I even heard about it before.
> 
> Not sure if you've tried other mining distros as a hardware benchmark, they all bring in different patches to the amd kernel driver, or plowed through available Hive versions to see if any of them is more stable?

Yes, I have tested multiple miners and I can get them to work with without rebooting, it is just that power consumption/hashrate is a LOT better in trm. Tried a few other hive versions too.

Last week I was able to keep it for 10 days straight and the issue was gone if I rebooted it, finally, but then new hive version and new trm version came out and oh crap, all that is back again. I'll keep messing around with the cards until I manage to keep it steady again.

**Comment by Kerney666** [comment]
It's really hard to see how the new TRM version could be the reason, the ethash kernels are identical in 0.8.5 and 0.8.6. We've seen a few funny issues with Asus Vegas, for some reason not liking the larger ethash+progpow binary.

So, I'd def start by rolling back to (or reinstalling) the Hive version that finally was working well for you. If you then experience the same problem on 0.8.6 but not on 0.8.5 (which I hope will work as well as before you upgraded things), please let me know. I'll keep the issue open for a little while longer.

**Comment by darkgodbm** [comment]
Things keep happening no matter what version I use or what settings I leave my cards with. I've been tampering with it for weeks, trying to find specific settings for each card or stuff like that, but no, it just won't stop it from happening. I'll send a screenshot of it so that you see it goes random between cards unless I stop the miner right after it starts, change something and restart miner without rebooting. If it reboots, same thing goes on again.
![Screenshot_20211030-075221](https://user-images.githubusercontent.com/91401938/139533125-1bdcb6e2-3991-4b2a-94fb-10c46e706e06.png)

**Comment by darkgodbm** [comment]
> It's really hard to see how the new TRM version could be the reason, the ethash kernels are identical in 0.8.5 and 0.8.6. We've seen a few funny issues with Asus Vegas, for some reason not liking the larger ethash+progpow binary, but that's it.
> 
> So, I'd def start by rolling back to (or reinstalling) the Hive version that finally was working well for you. If you then experience the same problem on 0.8.6 but not on 0.8.5 (which I hope will work as well as before you upgraded things), please let me know. I'll keep the issue open for a little while longer.

Sorry, forgot to quote you on previous comment as I wanted to
