### ISSUE TITLE
Monero switching to RandomX as early as October >.<

### ISSUE THREAD

**Issue by MoneroChan** [todxx/teamredminer#43]
Any plans to support Monero's RandomX? 

https://www.reddit.com/r/Monero/comments/b50mfy/logs_from_the_25_hr_dev_meeting_on_moneros_pow/

**Comment by cdarken** [comment]
RandomX is not for GPUs.

**Comment by MoneroChan** [comment]
Logic: 
TeamRed (ie; AMD) Makes CPUs
soTeamRedMiner Make CPU miner? XD

**Comment by MoneroChan** [comment]
Logic:
TeamRed (ie; AMD) Makes CPUs
so, TeamRedMiner Make CPU miner?

**Comment by todxx** [comment]
We've briefly looked at RandomX, and we don't currently see a good way to make it work on GPUs.
Currently we don't have plans to support RandomX at all, but much can change between now and October.
