### ISSUE TITLE
rpc times out every 69 seconds on supernova VTC

### ISSUE THREAD

**Issue by CryptoKnight614** [todxx/teamredminer#45]
I've tried the 3 rpc commands but they either make hashrate go to 0 or do nothing at all

**Comment by todxx** [comment]
Yes, this is a problem with some pools that don't support and properly handle extra nonce subscription.  Try using the `--pool_no_ensub` option.

**Comment by todxx** [comment]
Closing to due inactivity.  Please reopen if this issue is unresolved.
