### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm

### ISSUE THREAD

**Issue by gorgarp** [todxx/teamredminer#455]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin and is one of the fastest growing projects in the space.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. Your project looks extremely promising and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by MfA1907** [comment]
This would great for AMD owners who wanna mine flux on their rigs.

**Comment by MfA1907** [comment]
This would be great for AMD owners who wanna mine flux on their rigs.

**Comment by gorgarp** [comment]
Hello. Flux is now considered one of the 4 likely Eth replacements. Any thoughts?

**Comment by gorgarp** [comment]
Hello. Any update?

**Comment by gorgarp** [comment]
Hello,

Post merge we've increased our hashrate from 1.25 MSol/s up to 10MSol/s. Would love to know where this stands. As we continue this growth, we could use more quality mining software in the mix.

**Comment by Picio99** [comment]
@Teamredminer any news about mining flux? we are waiting your release for AMD
