### ISSUE TITLE
Only stratum+tcp and stratum+ssl URLs are supported

### ISSUE THREAD

**Issue by TheArctesian** [todxx/teamredminer#461]
Using a RX 5500 and getting this error when running 
```bash
./start_eth.sh 
```
error
```bash 
Only stratum+tcp and stratum+ssl URLs are supported.  Use option --help for usage.
```
if anyone knows why this is happening that would be a great help otherwise how do I run the --help command

**Comment by pdieppa** [comment]
Please post the content of start_eth.sh

**Comment by TheArctesian** [comment]
![2021-11-10_22-30](https://user-images.githubusercontent.com/87273292/141131846-e62d4e9a-f9ce-48cf-9c3b-6fa9da945271.png)

This is the message
![2021-11-10_22-32](https://user-images.githubusercontent.com/87273292/141132018-f01739e3-b380-4d2f-9020-0284a778c3d9.png)

This is my neofetch

**Comment by pdieppa** [comment]
We need the content of the file start_eth.sh to see why TRM is giving you that error.

**Comment by TheArctesian** [comment]
#!/bin/sh

# These environment variables should be set to for the driver to allow max mem allocation from the gpu(s).
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1

# Example batch file for starting teamredminer.  Please fill in all <fields> with the correct values for you.
# Format for running miner:
#      teamredminer.exe -a <algo> -o stratum+tcp://<pool address>:<pool port> -u <pool username/wallet> -p <pool password>
#
# Fields:
#      algo - the name of the algorithm to run. E.g. x16r or x16rv2
#      pool address - the host name of the pool stratum or it's IP address. E.g. lux.pickaxe.pro
#      pool port - the port of the pool's stratum to connect to.  E.g. 8332
#      pool username/wallet - For most pools, this is the wallet address you want to mine to.  Some pools require a username
#      pool password - For most pools this can be empty.  For pools using usernames, you may need to provide a password as configured on the pool.
#
# Example steps:
# 1. If you prefer a different pool, change the pool server address.
#
# 2. Replace the example wallet with your own wallet(!).
#
# 3. Name your worker by changing "trmtest" to your name of choice after the wallet below.
#
# 4. You're good to go!

./teamredminer -a ethash -o asia1.ethermine.org:4444 -u 0x206BcCF64aB61A0Bd90F97732625815aDe3AbD33.ARCH -p x

**Comment by pdieppa** [comment]
Change asia1.ethermine.org:4444 to asia1.ethermine.org:9999 and try it again

**Comment by TheArctesian** [comment]
Still the same

![2021-11-10_22-53](https://user-images.githubusercontent.com/87273292/141135925-8ad3459f-062f-44a1-9f40-3de5230fdd54.png)

**Comment by pdieppa** [comment]
Sorry 9999 is for a different pool.

Try 14444 instead of 9999

**Comment by pdieppa** [comment]
Also, place this in front of the pool name

stratum+tcp://

**Comment by pdieppa** [comment]
Ok, what GPU card(s) do you have?

**Comment by TheArctesian** [comment]
I'm testing rn with just an RX 5500, I have an ubuntu rig up with a two 3070s a 3080 and a 960 but just got a 2 5500 and wanted to put it on my test machine and mine at night. Was using the 960 on the test machine tho so I'm pretty sure my drivers are fucked

**Comment by pdieppa** [comment]
Keep upgrading the drivers until the AMD cards is detected.

Once thing I would recommend is to deploy HiveOs. It is based on Ubuntu but it is a dedicated platform for mining. It is not perfect but it comes with pretty much everything you need to get linux up and running. There are other linux based options out there but I have had very good luck with HiveOs,

**Comment by pdieppa** [comment]
My 5700XTs run perfectly under AMD 20.30

**Comment by TheArctesian** [comment]
Ayy bro we mining thanks for your help!
![2021-11-10_23-18](https://user-images.githubusercontent.com/87273292/141140403-87eecf38-3b1d-44ba-8b5c-33f1f8c69b79.png)
