### ISSUE TITLE
PCI bus in devs API method

### ISSUE THREAD

**Issue by akleandrov** [todxx/teamredminer#48]
Please add bus to gpu information

**Comment by Kerney666** [comment]
Hi!

This is already available. We added it to one of the available fields in the sgminer API, but I can't say we've documented it. If you check the new release (v0.4.5), there's a new howto guide on mapping gpus between miner/tools/win registry. That guide contains a section describing the field, it's in the DEVDETAILS api call iirc.

**Comment by akleandrov** [comment]
@Kerney666  I can`t found documentation

**Comment by todxx** [comment]
Closing old issue.  If you're still having these problems with the newer releases, please open a new issue.
