### ISSUE TITLE
new config for 0.44- updated help and config setting

### ISSUE THREAD

**Issue by rb116** [todxx/teamredminer#49]
Hi todxx,
Great to hear the new release but I am a bit confused about new setting especially interleave? I tried to read at bitcoin org but is not easy to filter the right content bcos some ppl will post e.g L24+24, some posted with * 16*14 but Power usage increased by 7% ( a lot). Some also posted new 1220 Gpu clock ? is this for CNR?  
I do hope u gives a message in the help file / OR update the First page the bitcoin org on wht shd be use (simple estimated guideline ).
Some also posted what is this? --CL 19 --RAS 30 --RCDRD 12 --RCDWR 6 --RC 44 --RP 13 --RRDS 5 --RRDL 5 --RTP 4 --FAW 18 --CWL 6 --WTRS 4 --WTRL 9 --WR 15 --WRRD 1 --RDWR 18 --REF 12800 --RFC 248 ?? really confusing.
 
Hope for new config for 0.44- updated help and config setting.. Pls. 
I am still using 0.40 for better pool hash/ stability for my Vega /RX550 rigs. 
P/S:  any changes for 0.44 on RX550? and can i assumed tht TRM default are using keepalive? do i need to add a parameter?

Pls Advice.

**Comment by rb116** [comment]
HI Todxx,

I am trying 0.44 ,without any changes to ALL setting and getting lower hash from miner , Power usage per Vega 56 GPu -5 W, Pool site hash reporting closer to miner dash.
Vega 56 Pulse ,default Bios. Hwinfo -Core 1397 to 1403 (875Mv), Mem 950-960Mhz (1.25V - Cant change).    ODT setting is Core 1413-1419 (890mv). Mem 950-960Mhz (mv not relevant). 
Power usage 149 down to 144W per GPU now.
Miner hash 12070h drop to 11750h now, Pool 11500 -> 11500.
16*14. this seems to gives me better hash on miner. As for Previous version, 16+14 gives better hash on miner and pool. 15+15 the worst for me.

Hv not try on 550rigs

**Comment by Kerney666** [comment]
Hi rb116!

Sorry for the belated reply. If you run your Vegas with modded timings, the new *-mode is indeed the one to use. For a Vega 56, I would expect one of 14*14, 15*15, 16*14 to be the best choice, but it varies between gpus.

In the recent releases, the *-mode and the tool you need to use to REALLY kill cnr with your Vegas is described in the CN_MAX_YOUR_VEGA.txt guide included in the .zip. Basically, you need to run a separare mem timings tool in your start .bat. That's the tool using the settings you posted in your initial comment for this issue.

If you get that tool going, you'll see a dramatic increase in hashrate for your Vegas. Trust me, it's worth the time :). That's also when you really need the *-mode.

**Comment by todxx** [comment]
Closing old issue.  If you're still having these problems with the newer releases, please open a new issue.
