### ISSUE TITLE
Power and hashrate drop with 5700 in B mode.

### ISSUE THREAD

**Issue by RolandWH** [todxx/teamredminer#490]
I have a 5700 (non-XT) and sometimes when using TRM in B mode the hash rate will randomly drop from ~50Mh/s to ~20Mh/s and the power will also drop from 115W to 80W.

Normally my mem temps are 96-100C (my card is the MSI Mech OC and it has a very bad cooler, will repaste/repad soon), after the issue they drop to about 75C so clearly the memory just isn't being stressed much anymore.

I do have monitors connected to the PC and use it for web browsing while mining. I do understand that A mode is the default with monitors connected but I was wondering if maybe there was a work around to stop this from happening, all shares do still show as valid on the Ethermine dashboard but as I said before hash rate is more than halved. The B mode intensity was auto-set by the miner to 446.

My OC Settings are as follows:
| Parameter | Stock Value | OC Value |
| --- | --- | --- |
| Core Voltage (mV) | 995 | 850 |
| Core Clock (MHz) | 1750 | 1300 |
| Mem Clock (MHz) | 1750 | 1824 |
| Fan Speed (%) | Auto | 80% |

Below you can see the full stats output of TRM before and after the issue occurs:
![trm_B_noissue](https://user-images.githubusercontent.com/45169084/147877718-bc7ea5c9-3fa5-40f4-ad49-54c1e1c32790.png)
![trm_B_issue](https://user-images.githubusercontent.com/45169084/147877717-21cfc69e-f16a-4359-9840-572c9cd88f19.png)

Thanks in advance for any replies 😀

**Comment by RolandWH** [comment]
UPDATE: It appears that this issue is fixed by closing and optionally reopening Google Chrome, a little annoying but no big deal. If there are no more comments soon I will close this issue.

**Comment by pdieppa** [comment]
You should do something about those memory temps. The chips are cooking at 98c and most likely the card is throttling back due to high temperature.

**Comment by RolandWH** [comment]
@pdieppa Yeah, I have ordered some replacement thermal pads and they will be arriving soon, I'm not sure that's the cause of the instability as the issue doesn't occur in A mode but either way it will be good to get those temps down.
