### ISSUE TITLE
Listen to STDIN so the miner can be programmatically (and cleanly) stopped

### ISSUE THREAD

**Issue by BinarSkugga** [todxx/teamredminer#496]
I made a simple python script that starts and stops the miner. However I can't figure anyway to cleanly stop it programmatically. Currently I use the `taskill` command of Windows but this results in the fan/clock settings not being reverted properly. Listening to the STDIN would allow my script to simply send a `q` command to the miner.

**Comment by todxx** [comment]
I believe using `os.Kill` to send a `signal.CTRL_C_EVENT` should do the trick, but I haven't tried it.  Let me know if that works for you.

**Comment by BinarSkugga** [comment]
Using `os.kill` or `process.send_signal` kill the subprocess correctly but also seem to kill the host process (the script doing the scheduling)

**Comment by todxx** [comment]
Maybe try overriding the CTRL_C_EVENT signal handler in the host process while you're trying to kill the subprocess and restore it once the subprocess has exited?

**Comment by BinarSkugga** [comment]
Yes this works correctly. I believe my host script was also closing because it didn't ignore the event. Overriding the default behavior for the `CTRL_C_EVENT` fixed it. Thank you !
