### ISSUE TITLE
Watchdog reboot ubuntu 16.04

### ISSUE THREAD

**Issue by milosz216** [todxx/teamredminer#52]
For month I was using TRM v4.2 mining miner in my ubuntu 16.04 machine. I configured auto start and watchdog that contain classic sh head and command “reboot”. Miner starting with sudo permissions into screen session. It was working just great for last month and rebooting machine if anyone card go off but couple days ago something starts to not working and watchdog just start to killing screen session instead of rebooting machine. I updated TRM to v4.4 but it doesn’t help.

**Comment by Kerney666** [comment]
Hmm. If it suddenly stopped working and you hadn't upgraded the miner, it's a little strange. That said, I did find one small thing that is fixed in the fresh v0.4.5 release, can you please try that and report back?

**Comment by milosz216** [comment]
today i updated the miner and it didn't helped

**Comment by todxx** [comment]
Closing old issue.  If you're still having these problems with the newer releases, please open a new issue.
