### ISSUE TITLE
wss ton pool connection

### ISSUE THREAD

**Issue by mbunal** [todxx/teamredminer#533]
how can i connect to wss:// ton pool?

wss://eu1.stratum.ton-pool.com/stratum
or 
https://next.ton-pool.club

**Comment by wl970930** [comment]
TRM supports three TON pools: Icemining, Ton Coin Pool, and Whales Ton
Pool using their tcp stratum endpoint. Whales Ton Pool needs wallet
registreation with their Telegram bot before starting to mine.
Use the following pool arguments to mine:

Icemining: -o stratum+tcp://ton.hashrate.to:4002 -u <ton wallet>.<worker> -p x

Ton Coin Pool: -o stratum+tcp://pplns.toncoinpool.io:443/stratum -u <ton wallet> -p <worker>

Whales Ton Pool: -o stratum+tcp://tcp.whalestonpool.com:4001 -u <ton wallet> -p x

**Comment by mbunal** [comment]
there is a proxy in trm package: trm_nimiq_proxy-linux 
can i use this proxy to connect to wss:// address?

**Comment by mbunal** [comment]
what was wrong?
`[2022-02-20 12:56:14] Pool eu1.stratum.ton-pool.com/stratum failed to resolve host address.
`
--init_style=3 --eth_config=B --eth_dag_buf=S --watchdog_script=/app-data/scripts/s01watchdog.sh --high_score --ton --ton_pool_mode=toncoinpool -o stratum+tcp://eu1.stratum.ton-pool.com:443/stratum -u MY_TON_ADDRESS.trm -p x --ton_end

**Comment by oiG8Uchi** [comment]
stratum.whalestonpool.com/stratum got this
![image](https://user-images.githubusercontent.com/95996550/154847277-ea0ba423-f30e-4f60-9ca8-6342d052f2d7.png)
[ trm_nimiq_proxy-linux 4443 stratum.whalestonpool.com/stratum 443 0 0
tcp.whalestonpool.com no such problems

**Comment by mbunal** [comment]
> o stratum+tcp://tcp.whalestonpool.com:4001

i can run with tonwhales but i want to run with ton-pool.com. please help!!!

**Comment by mbunal** [comment]
thanks for your effort....
