### ISSUE TITLE
Usability of PC when mining with 0.9.4 is horrible

### ISSUE THREAD

**Issue by cypher619** [todxx/teamredminer#555]
I mine on my daily driver PC and with the 0.9.4 release, usability is horrible.  I have tried adjusting the eth_config paramter without any improvment.  I have reverted to 0.9.3 in the mean time.  With 0.9.3 i can watch a mp4 video and play a non intensive graphics game in bluestacks.  With 0.9.4 video ouput lags and pc can even become unusable requiring a reboot when trying to do the same things.

Anyone having the same issue?

**Comment by MayBankCH** [comment]
Manually set  --dual_intensity=0.65

**Comment by cypher619** [comment]
Thank you!!  That helped make things right.  I had to go lower than 0.65 but knowing the parameter to tweak helped.
