### ISSUE TITLE
-d and/or --devices argument is not working

### ISSUE THREAD

**Issue by dk7988** [todxx/teamredminer#576]
hello, All of the following attempts did not work in my 5gpu rig. I'm trying to have gpu's 0,2,3,4 be run but trm and gpu 1 be ran by another miner. the result of all these tries is trm will run all the gpus regardless of -d and/or --devices arguments. In order to get gpu 1 up and working with the other miner i have to logon the miner and use the trm mining command d1 to pause this device from mining on trm. how do i fix this in my flight sheet? i'm using hiveOS,  gpu's 0,2,3,4 are 4gb 480s/580s gpu 1 is a 8gb 580. also using trm v.0.9.4.2

-d 0,2,3,4
--devices 0,2,3,4
-d=0,2,3,4
--devices=0,2,3,4
-d '0,2,3,4'
--devices '0,2,3,4'
-d='0,2,3,4'
--devices='0,2,3,4'

or 
thinking pci-e ordering i tried
-d 2,6,7,8
--devices 2,6,7,8
-d=2,6,7,8
--devices=2,6,7,8
-d '2,6,7,8'
--devices '2,6,7,8'
-d='2,6,7,8'
--devices='2,6,7,8'

and

-d 02,06,07,08
--devices 02,06,07,08
-d=02,06,07,08
--devices=02,06,07,08
-d '02,06,07,08'
--devices '02,06,07,08'
-d='02,06,07,08'
--devices='02,06,07,08'

or 

-d 0
--devices 0
-d=0
--devices=0
-d '0'
--devices '0'
-d='0'
--devices='0'

or 

-d 0
--devices 0
-d=0
--devices=0
-d '0'
--devices '0'
-d='0'
--devices='0'

**Comment by pdieppa** [comment]
Check the Tuning tab to make sure the trm settings are not overwritten by something there

**Comment by dk7988** [comment]
honestly i've never used this tab in hive but it looks pretty bare to me
![image](https://user-images.githubusercontent.com/84101017/161400313-b3d90f91-621f-436b-a9b4-0de3c44ac977.png)

**Comment by dk7988** [comment]
> Check the Tuning tab to make sure the trm settings are not overwritten by something there

Honestly i've never used this tab in hive but it looks pretty bare to me 
![image](https://user-images.githubusercontent.com/84101017/161400341-a548d48b-20be-4ec6-b564-31216877605f.png)

**Comment by pdieppa** [comment]
Please post a screenshot of the flightsheet.

**Comment by dk7988** [comment]
> 

![image](https://user-images.githubusercontent.com/84101017/161400579-1940ce12-0471-4da3-9c13-afc4d330ec57.png)

**Comment by pdieppa** [comment]
You are using the wrong section for the parameters. That belongs to the second algo. Use the top one.

**Comment by dk7988** [comment]
ahh.. like this.. i completely missed it.. :/ i'm use to there only being one
![image](https://user-images.githubusercontent.com/84101017/161400690-4dbc9fae-6e16-4dc7-8ff1-c41c846923b9.png)

**Comment by pdieppa** [comment]
That's much better.

**Comment by dk7988** [comment]
agreed!! thank you! 
![image](https://user-images.githubusercontent.com/84101017/161400756-8f0010f0-a3c1-4350-b630-23ed286d7b9b.png)
