### ISSUE TITLE
Max GPU's 

### ISSUE THREAD

**Issue by swreynolds1** [todxx/teamredminer#59]
What is the maximum amount of GPU's I can add to red miner?  Thanks!

**Comment by todxx** [comment]
Currently the miner will support up to 16 GPUs.  Please let us know if you need it to support more.

**Comment by UselessGuru** [comment]
> Currently the miner will support up to 16 GPUs.

How does device enumeration work for devices >= 10?

The help only gives me this:

```
  -d, --devices=DEVLIST     Sets gpu devices to use from detected list. DEVLIST should be a comma-
                              separated list of device indices, e.g. -d 0,1,2,4.  If not specified, all
                              devices on the platform(s) will be used.  NOTE: if using --bus_reorder, the
                              indices used are after reordering. Use --list_devices to show indices.
```

**Comment by todxx** [comment]
It should just be a decimal index, so something like `-d 8,9,10,11` should work.  Admittedly, I have not personally tried it as all my rigs are 8 gpus max.

**Comment by carrolltondatago** [comment]
I have a Gigabyte 12 GPU motherboard that I've been adding GPUs to one at a time.  At 5 GPU it works fine.  When I add number 6 it all falls apart.  It sees the correct number of GPU but there is always 1 that fails to initialize.  I've already set the minimum page file to 16gb and a max of 120gb.  Is there perhaps something else I've missed??
