### ISSUE TITLE
W5700 - Unexpected low hashrate using R-mode

### ISSUE THREAD

**Issue by AkiraDX** [todxx/teamredminer#594]
***Update***
Seem like v0.9.4.7 already solved this 

- [Hi.. Guys...

I don't know why I'm getting unusual low hashrate with my W5700
when running the new R-mode.

Each of the GPU will have different hashrate everytime I restart the miner.

I managed to received 50MH/s hashrate only 1GPU and only 1 time.

Increasing coreclock doesn't make any improvement on the hashrate.

![image](https://user-images.githubusercontent.com/83026901/167575340-ee3ae73d-ffb8-47c9-b9ce-9a3099159259.png)

![image](https://user-images.githubusercontent.com/83026901/167575587-1c29bc43-5fc7-4a15-8fb8-14dcea7798bf.png)
] issue.

**Comment by blackmennewstyle** [comment]
You are not the only one apparently, someone else reported some hash-rate issue with more than 6 GPUs #596 Hopefully the developers will fix it :)

**Comment by AkiraDX** [comment]
Update
Seem like v0.9.4.7 already solved this
