### ISSUE TITLE
Feature Request: Dynamic Pool Support

### ISSUE THREAD

**Issue by shimmervoid** [todxx/teamredminer#61]
Hello Teamred,

Can it be made possible for the miner to auto-detect algo's? Can it work in tandem with xmrig-proxy to  support dynamic pool swaps?  

Thanks again for your fabulous miner!!!

**Comment by todxx** [comment]
Hi @shimmervoid,

We don't currently plan to support native algo-switching in the miner, however we did add initial support for TRM to monero ocean's meta-miner script: https://github.com/MoneroOcean/meta-miner

At this point it's a couple versions out of date with the latest release of TRM, so it'll need a little updating to work with all the new algorithms.  We'll try to get an update for the latest version of TRM going for it.

**Comment by shimmervoid** [comment]
Oh!!! words cannot express....
I look forward to it.
