### ISSUE TITLE
Adding kaspa? Solo and pool 

### ISSUE THREAD

**Issue by CatStoleMyRvnCoin** [todxx/teamredminer#666]
Any plans for this?

Just wondering thanks for any response.

**Comment by CamJava007** [comment]
I agree... we all have literally been begging for this, and have heard nothing but crickets from the devs.

**Comment by CatStoleMyRvnCoin** [comment]
I like the number of this issue...

**Comment by CatStoleMyRvnCoin** [comment]
It's here. Top kek
