### ISSUE TITLE
FPGA Kaspa

### ISSUE THREAD

**Issue by AlexanderGalchenko** [todxx/teamredminer#668]
https://www.ospreyelectronics.io/product-page/e300-180m-eth-hash-rate 

they are start kaspa on FPGA. When you are add new algo to FPGA kard mining ?

I have FK33 and want to mine :)

**Comment by sman2600** [comment]
This is done in the 10.5 release.

**Comment by AlexanderGalchenko** [comment]
thank you. all works well.
