### ISSUE TITLE
Variable Core Clocks rx560

### ISSUE THREAD

**Issue by affyaff** [todxx/teamredminer#67]
Hi,

The core clock displayed for my Powercolor rx560s varies considerably every time I open the miner.
My core clocks are set to 1080 for both cards, however when I run TeamRed they often display as 214, 387, 856, or the full 1080.
The lower core clocks result in hashrates of between 30 and 170 H/s, and when working correctly they achieve 460H/s per card

This can be sometimes fixed just by rebooting the miner countless times.

Additionally, sometimes when the core clocks are both displaying at 1080, one card hashes at full capacity while the other continues to hash between 30 and 170.

The rig also contains 2x MSI Air Boost OC Vega 56 8GB
Any help is appreciated.

**Comment by todxx** [comment]
The miner doesn't directly adjust clocks on the cards, so nothing it is doing directly should be causing the clocks to change.

Have you checked the power consumption and temperatures on the cards?  Perhaps they are power or thermal throttling?

**Comment by affyaff** [comment]
Potentially mate, I seem to have fixed it now by playing around with OverdriveN settings.

Also since you can't message directly on github I just want to take the time to thank you and your team for this fucking incredible mining software update. This autotune feature is a godsend and I wouldn't be surprised if other developers copy your methods. 
Vega's are an absolute nightmare and optimising cards is a total ball ache for people like me who are only have intermediate knowledge of GPU setups.
I honestly can't put into words how amazing TeamRedMiner is, 2.5% dev fee is absolutely deserved if not a bit too low for what it does, keep it up lads/ladies.

**Comment by todxx** [comment]
Thank you very much for the very kind words.

We'll keep doing our best for as long as we can.  Things might get a bit tough when XMR forks away from CN.
