### ISSUE TITLE
Random x has AMD Vega Support upcoming and ON CUDA at least 1060-2060 series

### ISSUE THREAD

**Issue by SomethingGettingWrong** [todxx/teamredminer#68]
Any thoughts on adding support?  

https://github.com/SChernykh/RandomX_OpenCL
https://github.com/SChernykh/RandomX_CUDA

**Comment by todxx** [comment]
Unfortunately we don't see a way to achieve a GPU implementation that would have performance competitive with CPUs.  Given the large amount of development effort it would take to implement RandomX from scratch for GPUs, we can't really commit to it given how unprofitable the end result would be (both for miners and for us).

**Comment by SomethingGettingWrong** [comment]
Thankyou for your time!
