### ISSUE TITLE
rpc method "submit" timed out

### ISSUE THREAD

**Issue by ljcolomacks** [todxx/teamredminer#70]
I keep receiving the following error about ever 60 seconds. 

Pool <pool>.com rpc method "submit" timed out after 61 seconds.  Reconnecting.

I am using the following syntax in the script file.
./teamredminer -a cnr -o stratum+tcp://<pool>:7777 -u <address> -p x --cn_config=13*13:AAA --temp_limit=117 --pool_no_ensub

I have tried the --pool_no_ensub switch as well as --pool_broken_rpc and --pool_rpc_TO=SEC but has not seemed to make a difference. Also am getting the same error with the default pool in the autotune scripts. 

I am using an AMD Radeon VII  GPU running Ubuntu 18.04.2.

**Comment by todxx** [comment]
Hi, which version of the miner are you using?

**Comment by ljcolomacks** [comment]
I tried v0.5.3 as well as 0.5.2.

Thanks,
 Luke

**Comment by todxx** [comment]
Do you see any shares being accepted by the pool at all?
I just ran the run_autotune_quick.sh on an Ubuntu 18.04.2 rig with a VII and it ran without problems.
It's possible that you might have a firewall at some point blocking the network traffic.  I know some routers will occasionally block mining traffic.  Can you try running using an ssl connection?

**Comment by ljcolomacks** [comment]
Looks like you were spot on. Using SSL bypassed whatever was blocking the
connection. I didn’t notice shares were not being accepted as well. Thanks
for the help!

-Luke

**Comment by todxx** [comment]
Awesome, glad to help!
