### ISSUE TITLE
Feature request for PCI bus ID & OpenCL device ID matching / external tool?

### ISSUE THREAD

**Issue by UselessGuru** [todxx/teamredminer#71]
I am looking for a tool that reports PCI bus ID & matching OpenCL device ID. The reason:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2349

TRM can do this for AMD with --list_devices

but I am looking for something that does it for NVIDIA to.

I'd appreciate if you could lead me to a solution :-)

UselessGuru - co-developer of MultiPoolMiner.

**Comment by todxx** [comment]
Hi Guru,

The way TRM and other AMD miners do this is via a vendor specific OpenCL call that AMD provides in their OpenCL library.  Unfortunately we have little to no experience working with Nvidia CUDA/OpenCL APIs so I'm not sure how to do this for Nvidia cards.

I would suggest trying to find an open source miner that does PCIe enumeration for Nvidia cards and see how they manage it in their code.  Does ccminer list PCIe bus/dev ids?

Cheers,
todxx

**Comment by UselessGuru** [comment]
> Does ccminer list PCIe bus/dev ids

Unfortunately not. None of the open source miners do afaik.
