### ISSUE TITLE
x20 family

### ISSUE THREAD

**Issue by RGlabs84** [todxx/teamredminer#72]
LOVE HOW ROCK SOLID **STABLE** and **Efficient** this miner is, 24/7 up time on Vega 56 rig, no issues, however i'd love to see an algo expansion to bring that _**stability**_ to the **x20/x21 family**

**Comment by todxx** [comment]
We are currently working on other algorithms, and don't have plans to go into the x20/x21 families.  It is difficult to justify the amount of work to implement these algos when the userbases are relatively small and the coins that use them tend to fork POWs often.
