### ISSUE TITLE
AMD Radeon VII 16GB

### ISSUE THREAD

**Issue by nukepower** [todxx/teamredminer#73]
over heating mining MTP with the fan at 100 %  it goes up to 70 Or higher fast I only one atm with 4 Vega in that rig the Vega work great.

**Comment by ljcolomacks** [comment]
I am not part of teamredminer but figured I would give some input on this. Crit for the VII is 118C.
It's sensor layout is different than other cards. Mine settles around 103-110 with the fans at 70%. 
https://www.legitreviews.com/amd-radeon-vii-16gb-video-card-review_210489/13

**Comment by nukepower** [comment]
cool thanks for the link .    good to know 70 is no longer a worry with most AMD cards starting with the new ones.
