### ISSUE TITLE
Failed to initialize GPU - Initialization comm error 4

### ISSUE THREAD

**Issue by eyalkz** [todxx/teamredminer#74]
I'm using the latest version 0.5.5
Vega 56, Windows 10 Pro
Installed drivers 18.6.1
Errors:
Initialization comm error 4
Comm buf exit code timeout (20000002/0/126/271070532/1028353a).

**Comment by eyalkz** [comment]
![GPUz](https://user-images.githubusercontent.com/1984062/60919140-dae0f900-a249-11e9-87ec-38a574c7a60c.gif)

**Comment by todxx** [comment]
Hi, are you CPU mining while trying to start the miner by any chance?  Our init process is somewhat CPU intensive and can timeout if there is something using 100% of the system CPU power.

**Comment by OptiMysticall** [comment]
I found this comes up whenever I screw with my voltages on my GPU. Even on a fresh boot.. if the voltages aren't good or default.. This comes up.. So thought I would share in case anyone else comes across this issue. 

Set your GPU voltages to DEFAULT and Test.
