### ISSUE TITLE
Hashrate Not Updating in Pool Using TeamRedMiner with KawPow Algorithm

### ISSUE THREAD

**Issue by Rieidi** [todxx/teamredminer#786]
![IMG_20241215_111343790](https://github.com/user-attachments/assets/c914fe9f-03f0-48a8-8d1e-3a03a655a390)

Hello,

I’m experiencing an issue where my local hashrate in TeamRedMiner appears to be normal, but the hashrate in the pool does not update, even after mining for extended periods of time. Despite mining continuously, I don’t see any share acceptance or rejection, and the pool's dashboard keeps showing a 0 hashrate.

Here’s what I have done so far:

1. I am using TeamRedMiner with the KawPow algorithm.

2. I’ve double-checked my pool settings and miner configuration, and they appear to be correct.

3. I’ve already disabled both the firewall and antivirus software on my machine, as these might be blocking communication between the miner and the pool.

4. I’ve been mining for more than 22 minutes, but the pool still does not reflect any change in my hashrate or show any accepted or rejected shares.

I’m unsure what might be causing this issue. My miner is running without errors on the local side, but it seems like the communication with the pool is not functioning as expected.

Could anyone point me in the right direction or suggest steps to troubleshoot this further? I’d appreciate any help!

**Comment by atoi2008** [comment]
try to add --prog_hash_report to your command line options when starting.

**Comment by Rieidi** [comment]
Okay, I'll test this, but do you recommend that I use Windows 10 on a clean install instead of 11?

**Comment by atoi2008** [comment]
> Okay, I'll test this, but do you recommend that I use Windows 10 on a clean install instead of 11?

I wouldn't suggest that.

**Comment by Rieidi** [comment]
Even putting --prog_hash_report, nothing changed. Note: He is giving some HW. And by the way, shouldn't it be processing one job at a time?
![IMG_20241215_185700593](https://github.com/user-attachments/assets/5202fa91-aa7f-4c13-b6b3-339efd0cf933)

**Comment by angelbbs** [comment]
4Mh/s really? The miner will found the share in a couple of hours.

**Comment by Rieidi** [comment]
> 4Mh/s really? The miner will found the share in a couple of hours.

This card was actually supposed to reach 5 MH/s, but I'm having to limit it because of temperature.

**Comment by Rieidi** [comment]
GG, It's a VRAM problem... Probably physical degradation 
![IMG-20241216-WA0001](https://github.com/user-attachments/assets/9007bf45-7a22-4256-a41e-e7c0e2bc78b8)
