### ISSUE TITLE
Please, add RandomXL algorithm for Loki

### ISSUE THREAD

**Issue by Cideg** [todxx/teamredminer#80]
Begin by adding the RandomXL algorithm for Loki. The algorithm name used by the miner is randomx / loki or rx / loki.

Loki has a new fork, block 321467 -> RandomXL https://github.com/loki-project/loki/pull/675

**Comment by todxx** [comment]
Due to the extremely low performance of GPUs on randomx based algorithms, we will not be implementing any of them.
