### ISSUE TITLE
Vega64 crash with v0.5.6

### ISSUE THREAD

**Issue by equuleus** [todxx/teamredminer#81]
Something went wrong with 0.5.6 ("MTP improvements for Vega and Polaris (+1-3% hashrate, improved efficiency, esp Polaris)"). About 15% of all GPU (Vega 64, Ref, Air) crashing with 0.5.6 after several hours of stable working. Using lowering timings (from "CN_MAX_YOUR_VEGA.txt"), upping V in ram or gpu... nothing helps. With 0.5.1, 0.5.5 stable and everithing is fine (works more then 24H without errors).

**Comment by Kerney666** [comment]
Hi! Before I look into exactly what changed between 0.5.5 and 0.5.6, can you confirm your OS and driver, and also what algo(s) you've having troubles with? Also, it's a little interesting to know your mobo chipset (B250, H110+, etc), but no biggie if you don't have that data available.

**Comment by equuleus** [comment]
My mistake in version. I tested 0.5.1 and all newer versions all last week. Since 0.5.2 I have a bug. In 0.5.1 all hardware errors shows normal (if they a present), but in 0.5.2 it shows HW errors 0, but after several hours exit with error. OS: Win 10 Pro, 1903. Driver: 18.6.1 (24.20.11021.1000). Algo: CNR. Motherboard: ASRock H81 Pro BTC R2.0 (with P4 G3260).
[https://www.dropbox.com/s/pvnadldfby8bsd9/1.png?dl=0](url)

**Comment by todxx** [comment]
Closing old issue.  If the problem persists with the latest release, please reopen the issue.
