### ISSUE TITLE
Add Chukwa/Argon2 algo support to mine

### ISSUE THREAD

**Issue by mrnguyen-cn** [todxx/teamredminer#84]
Hello I want the algo Chukwa/Argon2 to be added on Teamredminer since WRKZ, BTCM, and TRTL are forking to that algo soon. It would be helpful if you add the algo in Teamredminer. Thank you.

**Comment by wrkzdev** [comment]
Thanks @mrnguyen-cn 

Hello dev,

Can you add add chukwa/wrkz or chukwa-256?

Regards,

**Comment by todxx** [comment]
Sorry, but at the moment we do not plan on adding support for other argon2 based algos.  As I mentioned in some of the other issues, it takes significant effort for us to add quality implementations of algos to our miner and we just don't have the time to implement many of the smaller algos out there.  If we see more demand by users in the future we will of course reconsider.
