### ISSUE TITLE
Vegas working on 0.5.7 don't work on 0.5.8

### ISSUE THREAD

**Issue by munhenhos** [todxx/teamredminer#89]
i'm running 6 vegas 56, samsung memory with the following tweaks: amdmemtweak --gpu 0,1,2,3,4,5 --CL 16 --RAS 30 --RCDRD 14 --RCDWR 14 --RC 44 --RP 14s --RRDS 3 --RRDL 5 --RTP 5 --FAW 20 --CWL 7 --WTRS 4 --WTRL 9 --WR 16 --WRRD 1 --RDWR 19 --REF 17550 --MRD 8 --MOD 15 --PD 8 --CKSRE 10 --CKSRX 10 --RFC 244
While running TDR 0.5.7 everything works ok. Hashrate around 12.3kH. 
If i change to TDR 0.5.8 the rig crashes on device 0. Even without the tweak and lowering the overclock it doesn't start to mine.

**Comment by RGlabs84** [comment]
Oh I see why your pissed about my post, it over shadows yours. 

Let start simple! Like providing basic information, like OS and Version, driver version etc etc. 

I bet half of you still use outdated "blockchain" drivers

**Comment by RGlabs84** [comment]
You have some kind of conflict, 4 Vega 56s and 2 rx550s work fine.  It's not a problem of the miner, as you said to me.

**Comment by munhenhos** [comment]
What's the hashrate of your vegas? What's the OS?
I'm using latest drivers on HiveOS.

**Comment by RGlabs84** [comment]
using newest amd drivers on windows 10(1903 newest) im getting about
22-24Mh/s per Vega in x16 core at 1475/mem650

**Comment by todxx** [comment]
It appears there is a bug in some versions of amdgpu-pro drivers that is more likely to big triggered by v0.5.8 than previous versions.  We've implemented a workaround for this bug in v0.5.9.

Can you please test the new version and check if your issues persist?

**Comment by munhenhos** [comment]
Of course, i'll give you feedback asap.

**Comment by munhenhos** [comment]
all good on 0.5.9.

**Comment by todxx** [comment]
Awesome!  Feels good to get some of these issues resolved :)
