### ISSUE TITLE
Need updated Algos!

### ISSUE THREAD

**Issue by RGlabs84** [todxx/teamredminer#90]
coins are forking left and right these days, we need to be abelt to keep up with the nvidia junkies! x16v2 for rvn and others, pgn is switching to x21, randomx is coming...

**Comment by munhenhos** [comment]
I don't think this is an issue of the miner. also, new algos have been added in the past releases. i suggest closing this.

**Comment by RGlabs84** [comment]
How is this not an issue? Okay so let it get outdated then.. LMAO.

**Comment by munhenhos** [comment]
It isn't a code issue or a bug. Your miner doesn't crash. This isn't twitter or facebook where people cry about their lives. Once again, close this.

**Comment by RGlabs84** [comment]
No one is crying about their life, except for you. I'm not the only person
on hear complaining about algo support, maybe try bugging them snowflake

**Comment by nn47nn** [comment]
Need, need, need!!!

**Comment by RGlabs84** [comment]
Love that 059 dropped today with x16v2. Thank you so much to the devs!!  Please please please add x21 support! Your miner destroys the competition on stability!

**Comment by todxx** [comment]
Hey guys, glad you're enjoying the x16rv2 in the new release.  We put a ton of effort into optimizing it for this release.

However, that ton of effort that it takes for us to release quality algo implementations is also why we must choose which algos we spend our time on.  Unfortunately x21 is not a very widely used algo and we can't justify the effort to implement it right now.  Regarding randomx, as we've said before, we don't see a way to implement it for GPUs in a way that will be remotely competitive with CPUs, and therefore we will not be implementing it.  We are constantly looking for and working on algos to implement, but we must pick and choose our battles.  We get many requests for many algos and unfortunately we just don't have the time to implement most of them.

**Comment by RGlabs84** [comment]
But x21 is about to receive more coins! ={
