### ISSUE TITLE
Vega flagging HW, on CN only

### ISSUE THREAD

**Issue by RGlabs84** [todxx/teamredminer#93]
I have Vega flagging HW error counts as jobs are being received or at random, can confirm that this only happens when running CN, i imagine when this is happening is why my display is doing little freezes, does not happen on any other algo

**Comment by ArSd-g** [comment]
Same here! arch-linux 5.3.1, Drivers 19.30, Vega 56 pulse Flashed, only 1 Gpu flags hw, all seems to be stable...

**Comment by RGlabs84** [comment]
My vega is pretty much useless for CN atm, if it does work, hashrate is 1600 and then drops fast til GPU Dead

Sent from Mail for Windows 10

**Comment by todxx** [comment]
The hw error count simply measures the number of shares reported by the GPUs that fail CPU verification.  If you see hw errors it means that the voltages/clocks/temps are not stable on that gpu.

**Comment by ArSd-g** [comment]
ok let's investigate so...not possible it's a cpu prob? i work with dual xeon (E5-2620V3) on a supermicro X10Drl-i motherboard...
I also want to know what do you think guys about 2 options i can set on this MB (jumpers):
- 2 jumpers to connect VRm to the BMC /OR/ PCH ???
- 2 jumpers to connect PCI Devices to SM-Bus (i2c) ???
- ECC Ram could be a problem?
- Needed BIOS options to be enabled/disabled on this server config??
-

**Comment by RGlabs84** [comment]
So then what's with my Vega ramp DOWN? Even when I adjust the card, it acts
as tho it can't mine with Polaris at same time?  Maybe later tonight
(eastern time) I'll try to screen record

**Comment by RGlabs84** [comment]
okay so i did a log! i also observed Hwinfo, once the hasrate starts to cut down, i notice a gpu power cycling from 60w to 114-140w depending on its load, it also shows 2 compute threads hitting 100% for a second or two, then both compute threads experience a very long off time, almost 4-7 seconds, heres the log. also, auto tune wont even run at this point, just sits at 0% so 2 logs here
[CNissues.txt](https://github.com/todxx/teamredminer/files/3705215/CNissues.txt)
[CNissues-autotune_quick_log-Vega.txt](https://github.com/todxx/teamredminer/files/3705216/CNissues-autotune_quick_log-Vega.txt)

**Comment by RGlabs84** [comment]
Reducing CN settings from L15+15 which would cause 2 compute threads on vega to CYCLE 100% back and forth, after leaving this issue alone for awhile and mining other things, returned to ticker!

While L15+15 produced 1600h/s which would cycles stats at that rate then procede to drop to 200h/s before declaring GPU dead

Set to L14+14, now mining at 2000h/s (1500/935) @130w both compute threads mine consistantly 80-90% with spikes to 100%, however, hash now remains constant @1999-2002h/s

My issues is resolved, closing case.
